export const englishTutorContent = {
  en: {
    hero: {
      eyebrow: "AI LANGUAGE IMMERSION",
      titleLine1: "The AI Tutor",
      titleLine2: "That Evolves",
      titleLine3: "With You.",
      subtitle: "An immersive language learning experience powered by adaptive artificial intelligence.",
      scroll: "SCROLL TO EXPLORE",
    },
    immersive: {
      eyebrow: "IMMERSIVE LEARNING",
      titleLine1: "Learning Through",
      titleLine2: "Real Conversation.",
      description: "Every interaction is personalized, context-aware and designed to evolve alongside the learner's progress.",
    },
    gamification: {
      eyebrow: "GAMIFICATION ENGINE",
      titleLine1: "Every Conversation",
      titleLine2: "Moves You Forward",
      subtitle: "Learning becomes measurable through XP, leagues, streaks and achievements.",
      xp: "0 XP",
      league: "Bronze League",
      stats: ["17 Day Streak", "96% Pronunciation", "250 Words Learned", "Top 3 Rank"],
    },
    adaptive: {
      eyebrow: "ADAPTIVE INTELLIGENCE",
      titleLine1: "Every Lesson",
      titleLine2: "Adapts To You.",
      subtitle: "The AI continuously analyzes performance, identifies weaknesses and creates a personalized learning journey in real time.",
      user: "YOU",
      metrics: [
        { label: "Pronunciation", value: "72%" },
        { label: "Vocabulary", value: "A2" },
        { label: "Grammar", value: "Weakness" },
      ],
      engine: "AI ENGINE",
      outputs: ["Lessons", "Feedback", "Challenges"],
      finalNode: "Personalized Growth",
    },
    architecture: {
      eyebrow: "TECHNICAL ARCHITECTURE",
      titleLine1: "The Intelligence",
      titleLine2: "Behind Every Lesson.",
      subtitle: "A modular architecture designed to analyze, adapt and continuously improve the learning experience.",
      user: "USER",
      conversation: "Conversation Engine",
      memoryLayer: "Memory Layer",
      memoryTags: ["Vocabulary", "Mistakes", "Confidence", "Goals", "Pronunciation"],
      aiCore: "Adaptive AI",
      feedbackEngine: "Feedback Engine",
      progressSystem: "Progress System",
    },
    impact: {
      eyebrow: "IMPACT & RESULTS",
      titleLine1: "Learning That",
      titleLine2: "Creates Results.",
      metrics: [
        { value: "0", label: "XP Earned" },
        { value: "96%", label: "Pronunciation Accuracy" },
        { value: "250+", label: "Words Learned" },
        { value: "17", label: "Day Streak" },
        { value: "89%", label: "Retention Rate" },
      ],
    },
    vision: {
      eyebrow: "PROJECT VISION",
      titleLine1: "The Future",
      titleLine2: "Of Language Learning.",
      subtitle: "An AI companion that remembers, adapts and grows with every learner.",
      pillars: [
        { icon: "brain", title: "AI Memory", desc: "Learning experiences that remember every interaction." },
        { icon: "zap", title: "Adaptive Learning", desc: "Lessons that evolve according to performance and goals." },
        { icon: "globe", title: "Human Connection", desc: "Technology designed to make learning natural and engaging." },
      ],
      quoteLine1: "Learning is no longer static.",
      quoteLine2: "It evolves with you.",
      modalLabel: "English Tutor showcase",
      slides: [
        { title: "AI Conversation Interface", description: "Immersive chat interface designed for real-time natural language processing and voice interaction." },
        { title: "Real-Time Grammar Feedback", description: "A feedback pipeline that analyzes mistakes on the fly with context-aware suggestions." },
        { title: "Fluency Analytics", description: "Deep insights into vocabulary growth, pronunciation accuracy and learner progress." },
      ],
    },
    mockup: {
      appName: "English AI",
      xp: "XP 5308",
      league: "Bronze League",
      listening: "AI is listening",
      userMessage1: "Hi, how are you?",
      aiMessage1: "Great start!",
      aiMessage2: "A more natural version:",
      aiSuggestion: "How are you doing today?",
      userMessage2: "I am good.",
      input: "Type or speak...",
      micLabel: "Start voice input",
      sendLabel: "Send message",
    },
  },
  pt: {
    hero: {
      eyebrow: "IMERSÃO EM IDIOMAS COM IA",
      titleLine1: "O Tutor com IA",
      titleLine2: "Que Evolui",
      titleLine3: "Com Você.",
      subtitle: "Uma experiência imersiva de aprendizado de idiomas impulsionada por inteligência artificial adaptativa.",
      scroll: "ROLE PARA EXPLORAR",
    },
    immersive: {
      eyebrow: "APRENDIZADO IMERSIVO",
      titleLine1: "Aprender Por Meio",
      titleLine2: "De Conversas Reais.",
      description: "Cada interação é personalizada, entende o contexto e evolui junto com o progresso do estudante.",
    },
    gamification: {
      eyebrow: "MOTOR DE GAMIFICAÇÃO",
      titleLine1: "Cada Conversa",
      titleLine2: "Leva Você Adiante",
      subtitle: "O aprendizado se torna mensurável com XP, ligas, sequências e conquistas.",
      xp: "0 XP",
      league: "Liga Bronze",
      stats: ["17 Dias em Sequência", "96% Pronúncia", "250 Palavras Aprendidas", "Top 3 Ranking"],
    },
    adaptive: {
      eyebrow: "INTELIGÊNCIA ADAPTATIVA",
      titleLine1: "Cada Aula",
      titleLine2: "Se Adapta a Você.",
      subtitle: "A IA analisa continuamente a performance, identifica fraquezas e cria uma jornada personalizada em tempo real.",
      user: "VOCÊ",
      metrics: [
        { label: "Pronúncia", value: "72%" },
        { label: "Vocabulário", value: "A2" },
        { label: "Gramática", value: "Fraqueza" },
      ],
      engine: "MOTOR DE IA",
      outputs: ["Aulas", "Feedback", "Desafios"],
      finalNode: "Crescimento Personalizado",
    },
    architecture: {
      eyebrow: "ARQUITETURA TÉCNICA",
      titleLine1: "A Inteligência",
      titleLine2: "Por Trás de Cada Aula.",
      subtitle: "Uma arquitetura modular criada para analisar, adaptar e melhorar continuamente a experiência de aprendizado.",
      user: "USUÁRIO",
      conversation: "Motor de Conversação",
      memoryLayer: "Camada de Memória",
      memoryTags: ["Vocabulário", "Erros", "Confiança", "Objetivos", "Pronúncia"],
      aiCore: "IA Adaptativa",
      feedbackEngine: "Motor de Feedback",
      progressSystem: "Sistema de Progresso",
    },
    impact: {
      eyebrow: "IMPACTO & RESULTADOS",
      titleLine1: "Aprendizado Que",
      titleLine2: "Gera Resultados.",
      metrics: [
        { value: "0", label: "XP Ganho" },
        { value: "96%", label: "Precisão de Pronúncia" },
        { value: "250+", label: "Palavras Aprendidas" },
        { value: "17", label: "Dias em Sequência" },
        { value: "89%", label: "Taxa de Retenção" },
      ],
    },
    vision: {
      eyebrow: "VISÃO DO PROJETO",
      titleLine1: "O Futuro",
      titleLine2: "Do Aprendizado de Idiomas.",
      subtitle: "Um companheiro de IA que lembra, adapta e cresce com cada estudante.",
      pillars: [
        { icon: "brain", title: "Memória de IA", desc: "Experiências de aprendizado que lembram cada interação." },
        { icon: "zap", title: "Aprendizado Adaptativo", desc: "Aulas que evoluem conforme performance e objetivos." },
        { icon: "globe", title: "Conexão Humana", desc: "Tecnologia desenhada para tornar o aprendizado natural e envolvente." },
      ],
      quoteLine1: "Aprender não é mais estático.",
      quoteLine2: "Evolui com você.",
      modalLabel: "Showcase do English Tutor",
      slides: [
        { title: "Interface de Conversação com IA", description: "Chat imersivo criado para processamento de linguagem natural e interação por voz em tempo real." },
        { title: "Feedback Gramatical em Tempo Real", description: "Pipeline de feedback que analisa erros na hora com sugestões contextuais." },
        { title: "Análises de Fluência", description: "Insights profundos sobre crescimento de vocabulário, precisão de pronúncia e progresso do estudante." },
      ],
    },
    mockup: {
      appName: "English AI",
      xp: "XP 5308",
      league: "Liga Bronze",
      listening: "IA ouvindo",
      userMessage1: "Hi, how are you?",
      aiMessage1: "Ótimo começo!",
      aiMessage2: "Uma versão mais natural:",
      aiSuggestion: "How are you doing today?",
      userMessage2: "I am good.",
      input: "Digite ou fale...",
      micLabel: "Iniciar entrada por voz",
      sendLabel: "Enviar mensagem",
    },
  },
  es: {
    hero: {
      eyebrow: "INMERSIÓN LINGÜÍSTICA CON IA",
      titleLine1: "El Tutor con IA",
      titleLine2: "Que Evoluciona",
      titleLine3: "Contigo.",
      subtitle: "Una experiencia inmersiva de aprendizaje de idiomas impulsada por inteligencia artificial adaptativa.",
      scroll: "DESPLAZA PARA EXPLORAR",
    },
    immersive: {
      eyebrow: "APRENDIZAJE INMERSIVO",
      titleLine1: "Aprender Mediante",
      titleLine2: "Conversaciones Reales.",
      description: "Cada interacción es personalizada, entiende el contexto y evoluciona junto al progreso del estudiante.",
    },
    gamification: {
      eyebrow: "MOTOR DE GAMIFICACIÓN",
      titleLine1: "Cada Conversación",
      titleLine2: "Te Impulsa Adelante",
      subtitle: "El aprendizaje se vuelve medible con XP, ligas, rachas y logros.",
      xp: "0 XP",
      league: "Liga Bronce",
      stats: ["17 Días de Racha", "96% Pronunciación", "250 Palabras Aprendidas", "Top 3 Ranking"],
    },
    adaptive: {
      eyebrow: "INTELIGENCIA ADAPTATIVA",
      titleLine1: "Cada Lección",
      titleLine2: "Se Adapta a Ti.",
      subtitle: "La IA analiza continuamente el rendimiento, identifica debilidades y crea una ruta personalizada en tiempo real.",
      user: "TÚ",
      metrics: [
        { label: "Pronunciación", value: "72%" },
        { label: "Vocabulario", value: "A2" },
        { label: "Gramática", value: "Debilidad" },
      ],
      engine: "MOTOR DE IA",
      outputs: ["Lecciones", "Feedback", "Desafíos"],
      finalNode: "Crecimiento Personalizado",
    },
    architecture: {
      eyebrow: "ARQUITECTURA TÉCNICA",
      titleLine1: "La Inteligencia",
      titleLine2: "Detrás de Cada Lección.",
      subtitle: "Una arquitectura modular creada para analizar, adaptar y mejorar continuamente la experiencia de aprendizaje.",
      user: "USUARIO",
      conversation: "Motor de Conversación",
      memoryLayer: "Capa de Memoria",
      memoryTags: ["Vocabulario", "Errores", "Confianza", "Objetivos", "Pronunciación"],
      aiCore: "IA Adaptativa",
      feedbackEngine: "Motor de Feedback",
      progressSystem: "Sistema de Progreso",
    },
    impact: {
      eyebrow: "IMPACTO Y RESULTADOS",
      titleLine1: "Aprendizaje Que",
      titleLine2: "Genera Resultados.",
      metrics: [
        { value: "0", label: "XP Ganado" },
        { value: "96%", label: "Precisión de Pronunciación" },
        { value: "250+", label: "Palabras Aprendidas" },
        { value: "17", label: "Días de Racha" },
        { value: "89%", label: "Tasa de Retención" },
      ],
    },
    vision: {
      eyebrow: "VISIÓN DEL PROYECTO",
      titleLine1: "El Futuro",
      titleLine2: "Del Aprendizaje de Idiomas.",
      subtitle: "Un compañero de IA que recuerda, se adapta y crece con cada estudiante.",
      pillars: [
        { icon: "brain", title: "Memoria de IA", desc: "Experiencias de aprendizaje que recuerdan cada interacción." },
        { icon: "zap", title: "Aprendizaje Adaptativo", desc: "Lecciones que evolucionan según rendimiento y objetivos." },
        { icon: "globe", title: "Conexión Humana", desc: "Tecnología diseñada para hacer el aprendizaje natural y atractivo." },
      ],
      quoteLine1: "Aprender ya no es estático.",
      quoteLine2: "Evoluciona contigo.",
      modalLabel: "Showcase de English Tutor",
      slides: [
        { title: "Interfaz de Conversación con IA", description: "Chat inmersivo diseñado para procesamiento de lenguaje natural e interacción por voz en tiempo real." },
        { title: "Feedback Gramatical en Tiempo Real", description: "Pipeline de feedback que analiza errores al instante con sugerencias contextuales." },
        { title: "Análisis de Fluidez", description: "Insights profundos sobre crecimiento de vocabulario, precisión de pronunciación y progreso del estudiante." },
      ],
    },
    mockup: {
      appName: "English AI",
      xp: "XP 5308",
      league: "Liga Bronce",
      listening: "IA escuchando",
      userMessage1: "Hi, how are you?",
      aiMessage1: "¡Buen comienzo!",
      aiMessage2: "Una versión más natural:",
      aiSuggestion: "How are you doing today?",
      userMessage2: "I am good.",
      input: "Escribe o habla...",
      micLabel: "Iniciar entrada por voz",
      sendLabel: "Enviar mensaje",
    },
  },
} as const;
