export const englishTutorContent = {
  en: {
    hero: {
      eyebrow: "Case Study // AI Polyglot Tutor",
      titleLine1: "A Tutor",
      titleLine2: "Guided by",
      titleLine3: "Pedagogy.",
      subtitle: "A language learning app where conversation, correction and progression are guided by a deterministic Teacher Brain before the local LLM writes the final response.",
      scroll: "SCROLL TO EXPLORE",
    },
    immersive: {
      eyebrow: "Problem",
      titleLine1: "Conversation Alone",
      titleLine2: "Is Not Teaching.",
      description: "Generic chat can sound fluent while missing the learner's level, recurring mistakes and next step. This case starts from the need to separate natural conversation from a clear pedagogical method.",
    },
    gamification: {
      eyebrow: "Solution // Practice Loop",
      titleLine1: "Every Session",
      titleLine2: "Needs Continuity",
      subtitle: "Gamification is treated as a routine layer: XP, streaks, levels and missions help practice feel visible without replacing the teaching logic.",
      xp: "0 XP",
      league: "Bronze League",
      stats: ["Daily Streaks", "XP Progress", "Scenario Missions", "Achievement Badges"],
    },
    adaptive: {
      eyebrow: "Engineering Decision",
      titleLine1: "Rules Before",
      titleLine2: "Generation.",
      subtitle: "The Teacher Brain decides the teaching move from stored progress, grammar signals and conversation context before the model writes the natural-language response.",
      user: "YOU",
      metrics: [
        { label: "Progress", value: "CEFR" },
        { label: "Memory", value: "SQL" },
        { label: "Guidance", value: "Rules" },
      ],
      engine: "TEACHER BRAIN",
      outputs: ["Conversation", "Correction", "Missions"],
      finalNode: "Guided Learning Loop",
    },
    architecture: {
      eyebrow: "Technical Architecture",
      titleLine1: "A Hybrid",
      titleLine2: "Teaching System.",
      subtitle: "The architecture keeps pedagogy in the application layer: rules decide the learning intent, memory preserves context, and the language model turns that intent into a response.",
      user: "USER",
      conversation: "Conversation Engine",
      memoryLayer: "Memory Layer",
      memoryTags: ["Vocabulary", "Mistakes", "CEFR", "Scenarios", "Progress"],
      aiCore: "Local LLM",
      feedbackEngine: "Feedback Engine",
      progressSystem: "Progress System",
    },
    impact: {
      eyebrow: "Evidence & Results",
      titleLine1: "Designed for",
      titleLine2: "A Clear Method.",
      metrics: [
        { value: "CEFR", label: "Progress Model" },
        { value: "Rules", label: "Teacher Brain" },
        { value: "Local", label: "LLM Runtime" },
        { value: "XP", label: "Practice Loop" },
        { value: "Missions", label: "Scenario Practice" },
      ],
    },
    vision: {
      eyebrow: "Result",
      titleLine1: "Learning With",
      titleLine2: "A Teaching Spine.",
      subtitle: "The result is a tutor concept built around a clear loop: listen, diagnose, guide, explain and keep the learner moving while evidence work continues.",
      pillars: [
        { icon: "brain", title: "Structured Memory", desc: "Progress, vocabulary and recurring mistakes can be stored as part of the learning context." },
        { icon: "zap", title: "Adaptive Guidance", desc: "The Teacher Brain chooses the next teaching move from grammar, scenario and progress signals." },
        { icon: "globe", title: "Human Conversation", desc: "Conversation stays central, while translation and explanation remain available when the learner needs support." },
      ],
      quoteLine1: "The model writes the response.",
      quoteLine2: "The pedagogy guides the lesson.",
      modalLabel: "English Tutor showcase",
      slides: [
        { title: "Conversation Interface", description: "A chat surface designed to keep natural practice close to translation, correction and explanation." },
        { title: "Pedagogical Feedback", description: "Feedback is framed as a teaching move selected from context, not as a guarantee of perfect grammar judgment." },
        { title: "Progress Context", description: "CEFR level, vocabulary, mistakes and scenario practice define the evidence path for the next validation phase." },
      ],
    },
    mockup: {
      appName: "English AI",
      xp: "XP Flow",
      league: "Bronze League",
      listening: "AI is listening",
      userMessage1: "Hi, how are you?",
      aiMessage1: "Great start!",
      aiMessage2: "A more natural version:",
      aiSuggestion: "How are you doing today?",
      userMessage2: "I am good.",
      input: "Type or speak...",
      micLabel: "Start voice input",
      sendLabel: "Send message",
    },
  },
  pt: {
    hero: {
      eyebrow: "Estudo de Caso // AI Polyglot Tutor",
      titleLine1: "Um Tutor",
      titleLine2: "Guiado por",
      titleLine3: "Pedagogia.",
      subtitle: "Um app de aprendizado de idiomas em que conversa, correção e progressão são guiadas por um Teacher Brain determinístico antes do LLM local escrever a resposta final.",
      scroll: "ROLE PARA EXPLORAR",
    },
    immersive: {
      eyebrow: "Problema",
      titleLine1: "Conversa Sozinha",
      titleLine2: "Não É Ensino.",
      description: "Um chat genérico pode soar fluente enquanto ignora nível, erros recorrentes e próximo passo do estudante. Este case parte da necessidade de separar conversa natural de um método pedagógico claro.",
    },
    gamification: {
      eyebrow: "Solução // Loop de Prática",
      titleLine1: "Toda Sessão",
      titleLine2: "Precisa de Continuidade",
      subtitle: "Gamificação entra como camada de rotina: XP, sequências, níveis e missões ajudam a prática a ficar visível sem substituir a lógica de ensino.",
      xp: "0 XP",
      league: "Liga Bronze",
      stats: ["Sequências Diárias", "Progresso de XP", "Missões por Cenário", "Conquistas"],
    },
    adaptive: {
      eyebrow: "Decisão de Engenharia",
      titleLine1: "Regras Antes",
      titleLine2: "Da Geração.",
      subtitle: "O Teacher Brain decide o movimento pedagógico a partir de progresso salvo, sinais gramaticais e contexto da conversa antes do modelo escrever a resposta em linguagem natural.",
      user: "VOCÊ",
      metrics: [
        { label: "Progresso", value: "CEFR" },
        { label: "Memória", value: "SQL" },
        { label: "Orientação", value: "Regras" },
      ],
      engine: "TEACHER BRAIN",
      outputs: ["Conversa", "Correção", "Missões"],
      finalNode: "Loop de Aprendizado Guiado",
    },
    architecture: {
      eyebrow: "Arquitetura Técnica",
      titleLine1: "Um Sistema",
      titleLine2: "Híbrido de Ensino.",
      subtitle: "A arquitetura mantém a pedagogia na camada da aplicação: regras decidem a intenção de aprendizado, memória preserva contexto e o modelo de linguagem transforma essa intenção em resposta.",
      user: "USUÁRIO",
      conversation: "Motor de Conversa",
      memoryLayer: "Camada de Memória",
      memoryTags: ["Vocabulário", "Erros", "CEFR", "Cenários", "Progresso"],
      aiCore: "LLM Local",
      feedbackEngine: "Motor de Feedback",
      progressSystem: "Sistema de Progresso",
    },
    impact: {
      eyebrow: "Evidência & Resultado",
      titleLine1: "Projetado para",
      titleLine2: "Um Método Claro.",
      metrics: [
        { value: "CEFR", label: "Modelo de Progresso" },
        { value: "Regras", label: "Teacher Brain" },
        { value: "Local", label: "Runtime do LLM" },
        { value: "XP", label: "Loop de Prática" },
        { value: "Missões", label: "Prática por Cenário" },
      ],
    },
    vision: {
      eyebrow: "Resultado",
      titleLine1: "Aprendizado Com",
      titleLine2: "Espinha Pedagógica.",
      subtitle: "O resultado é um conceito de tutor construído em torno de um loop claro: ouvir, diagnosticar, orientar, explicar e manter o estudante avançando enquanto a camada de evidências evolui.",
      pillars: [
        { icon: "brain", title: "Memória Estruturada", desc: "Progresso, vocabulário e erros recorrentes podem ser salvos como parte do contexto de aprendizado." },
        { icon: "zap", title: "Orientação Adaptativa", desc: "O Teacher Brain escolhe o próximo movimento de ensino a partir de gramática, cenário e progresso." },
        { icon: "globe", title: "Conversa Humana", desc: "A conversa continua central, enquanto tradução e explicação ficam disponíveis quando o estudante precisa de apoio." },
      ],
      quoteLine1: "O modelo escreve a resposta.",
      quoteLine2: "A pedagogia guia a aula.",
      modalLabel: "Showcase do English Tutor",
      slides: [
        { title: "Interface de Conversa", description: "Uma superfície de chat pensada para manter prática natural próxima de tradução, correção e explicação." },
        { title: "Feedback Pedagógico", description: "O feedback é tratado como movimento de ensino escolhido por contexto, não como garantia de julgamento gramatical perfeito." },
        { title: "Contexto de Progresso", description: "Nível CEFR, vocabulário, erros e prática por cenário definem o caminho de evidência para a próxima fase de validação." },
      ],
    },
    mockup: {
      appName: "English AI",
      xp: "XP Flow",
      league: "Liga Bronze",
      listening: "IA ouvindo",
      userMessage1: "Hi, how are you?",
      aiMessage1: "Ótimo começo!",
      aiMessage2: "Uma versão mais natural:",
      aiSuggestion: "How are you doing today?",
      userMessage2: "I am good.",
      input: "Digite ou fale...",
      micLabel: "Iniciar entrada por voz",
      sendLabel: "Enviar mensagem",
    },
  },
  es: {
    hero: {
      eyebrow: "Caso de Estudio // AI Polyglot Tutor",
      titleLine1: "Un Tutor",
      titleLine2: "Guiado por",
      titleLine3: "Pedagogía.",
      subtitle: "Una app de aprendizaje de idiomas donde conversación, corrección y progresión son guiadas por un Teacher Brain determinístico antes de que el LLM local escriba la respuesta final.",
      scroll: "DESPLAZA PARA EXPLORAR",
    },
    immersive: {
      eyebrow: "Problema",
      titleLine1: "Conversar Solo",
      titleLine2: "No Es Enseñar.",
      description: "Un chat genérico puede sonar fluido mientras ignora nivel, errores recurrentes y siguiente paso del estudiante. Este caso parte de la necesidad de separar conversación natural de un método pedagógico claro.",
    },
    gamification: {
      eyebrow: "Solución // Loop de Práctica",
      titleLine1: "Cada Sesión",
      titleLine2: "Necesita Continuidad",
      subtitle: "La gamificación entra como capa de rutina: XP, rachas, niveles y misiones ayudan a que la práctica sea visible sin reemplazar la lógica de enseñanza.",
      xp: "0 XP",
      league: "Liga Bronce",
      stats: ["Rachas Diarias", "Progreso de XP", "Misiones por Escenario", "Logros"],
    },
    adaptive: {
      eyebrow: "Decisión de Ingeniería",
      titleLine1: "Reglas Antes",
      titleLine2: "De Generar.",
      subtitle: "El Teacher Brain decide el movimiento pedagógico a partir de progreso guardado, señales gramaticales y contexto de conversación antes de que el modelo escriba la respuesta en lenguaje natural.",
      user: "TÚ",
      metrics: [
        { label: "Progreso", value: "CEFR" },
        { label: "Memoria", value: "SQL" },
        { label: "Guía", value: "Reglas" },
      ],
      engine: "TEACHER BRAIN",
      outputs: ["Conversación", "Corrección", "Misiones"],
      finalNode: "Loop de Aprendizaje Guiado",
    },
    architecture: {
      eyebrow: "Arquitectura Técnica",
      titleLine1: "Un Sistema",
      titleLine2: "Híbrido de Enseñanza.",
      subtitle: "La arquitectura mantiene la pedagogía en la capa de aplicación: reglas deciden la intención de aprendizaje, memoria preserva contexto y el modelo de lenguaje transforma esa intención en respuesta.",
      user: "USUARIO",
      conversation: "Motor de Conversación",
      memoryLayer: "Capa de Memoria",
      memoryTags: ["Vocabulario", "Errores", "CEFR", "Escenarios", "Progreso"],
      aiCore: "LLM Local",
      feedbackEngine: "Motor de Feedback",
      progressSystem: "Sistema de Progreso",
    },
    impact: {
      eyebrow: "Evidencia & Resultado",
      titleLine1: "Diseñado para",
      titleLine2: "Un Método Claro.",
      metrics: [
        { value: "CEFR", label: "Modelo de Progreso" },
        { value: "Reglas", label: "Teacher Brain" },
        { value: "Local", label: "Runtime del LLM" },
        { value: "XP", label: "Loop de Práctica" },
        { value: "Misiones", label: "Práctica por Escenario" },
      ],
    },
    vision: {
      eyebrow: "Resultado",
      titleLine1: "Aprendizaje Con",
      titleLine2: "Columna Pedagógica.",
      subtitle: "El resultado es un concepto de tutor construido alrededor de un loop claro: escuchar, diagnosticar, guiar, explicar y mantener al estudiante avanzando mientras la capa de evidencias evoluciona.",
      pillars: [
        { icon: "brain", title: "Memoria Estructurada", desc: "Progreso, vocabulario y errores recurrentes pueden guardarse como parte del contexto de aprendizaje." },
        { icon: "zap", title: "Guía Adaptativa", desc: "El Teacher Brain elige el siguiente movimiento de enseñanza a partir de gramática, escenario y progreso." },
        { icon: "globe", title: "Conversación Humana", desc: "La conversación sigue siendo central, mientras traducción y explicación quedan disponibles cuando el estudiante necesita apoyo." },
      ],
      quoteLine1: "El modelo escribe la respuesta.",
      quoteLine2: "La pedagogía guía la lección.",
      modalLabel: "Showcase de English Tutor",
      slides: [
        { title: "Interfaz de Conversación", description: "Una superficie de chat pensada para mantener práctica natural cerca de traducción, corrección y explicación." },
        { title: "Feedback Pedagógico", description: "El feedback se trata como movimiento de enseñanza elegido por contexto, no como garantía de juicio gramatical perfecto." },
        { title: "Contexto de Progreso", description: "Nivel CEFR, vocabulario, errores y práctica por escenario definen el camino de evidencia para la próxima fase de validación." },
      ],
    },
    mockup: {
      appName: "English AI",
      xp: "XP Flow",
      league: "Liga Bronce",
      listening: "IA escuchando",
      userMessage1: "Hi, how are you?",
      aiMessage1: "¡Buen comienzo!",
      aiMessage2: "Una versión más natural:",
      aiSuggestion: "How are you doing today?",
      userMessage2: "I am good.",
      input: "Escribe o habla...",
      micLabel: "Iniciar entrada por voz",
      sendLabel: "Enviar mensaje",
    },
  },
} as const;