export const musicPlayerContent = {
  en: {
    hero: {
      badge: "Case Study // Music Player",
      titleLine1: "Engineered",
      titleLine2: "for immersive",
      titleLine3: "listening.",
      description: "A premium local-first music experience crafted with cinematic motion, high-performance rendering and immersive interface design.",
    },
    device: {
      badge: "Product Experience",
      titleLine1: "Built to feel",
      titleAccent: "alive.",
      description: "Designed as a premium music ecosystem focused on music from devices, with immersive interactions, fluid rendering, and cinematic interface movements.",
      initializing: "Initializing",
      standby: "Ecosystem_Standby",
    },
    story: {
      chapter: "Chapter",
      steps: [
        {
          tag: "Gateway / Experience",
          title: "Initial Hub Architecture",
          desc: "The home screen sets the tone with clever contextual situations and responsive three-dimensional cards.",
        },
        {
          tag: "System / Navigation",
          title: "High-Fidelity Side Menu",
          desc: "A side panel designed for absolute control with advanced equalization and surgical navigation.",
        },
        {
          tag: "Ecosystem / Customization",
          title: "Functional Minimalism",
          desc: "A playlist journey designed to reduce cognitive load through strategic negative space.",
        },
        {
          tag: "Interactions / Modals",
          title: "Fluid Micro-Interactions",
          desc: "Smooth modals with visual depth and cinematic Gaussian blurs.",
        },
        {
          tag: "Data Curation / Playlists",
          title: "Advanced Management",
          desc: "Modular organization of local libraries with instant feedback and dynamic metadata.",
        },
        {
          tag: "Immersion / Audio Engine",
          title: "The Choreographic and Functional Player",
          desc: "Vivid volumetric gradients and reactive lighting synchronized with the sound atmosphere.",
        },
      ],
    },
    audio: {
      badge: "Audio Immersion",
      titleLine1: "Feel every",
      titleLine2: "frequency.",
      description: "A cinematic audio engine crafted to transform offline listening into an immersive sensory experience with reactive visuals.",
    },
    performance: {
      badge: "Performance Engineering",
      titleLine1: "Built for",
      titleLine2: "speed.",
      description: "Every rendering pipeline, animation layer and playback interaction was engineered for high refresh-rate fluidity and production-grade performance stability.",
      metrics: [
        { value: "< 1.8s", label: "Cold Start", desc: "Ultra-fast startup optimized for mid-range devices." },
        { value: "120 FPS", label: "Fluid Rendering", desc: "Stable cinematic motion with minimal frame drops." },
        { value: "99.5%", label: "Crash-Free Sessions", desc: "Production-grade reliability and runtime stability." },
        { value: "JANK <1%", label: "Rendering Stability", desc: "Carefully optimized rebuild and animation pipeline." },
      ],
    },
    architecture: {
      badge: "System Architecture",
      titleLine1: "Engineered",
      titleLine2: "for scale.",
      description: "A modular audio architecture designed for stability, rendering performance and scalable playback orchestration across platforms.",
      nodeDescription: "Optimized orchestration layer for premium audio rendering.",
      active: "Active",
      items: ["Playback Engine", "Audio Session", "Queue Controller", "Artwork Pipeline", "Cache Layer", "UI Rendering"],
    },
    design: {
      badge: "Design System",
      titleLine1: "Consistency",
      titleLine2: "at scale.",
      description: "A cohesive interface system designed with adaptive spacing, cinematic motion and scalable visual hierarchy across platforms.",
      typographyScale: "Typography Scale",
      display: "Display",
      cinematicHierarchy: "Cinematic hierarchy",
      typographyDescription: "Carefully balanced typography system designed for readability, rhythm and immersive visual composition.",
      tokens: [
        { title: "Typography", value: "Display / Editorial", desc: "Large-scale cinematic typography engineered for immersive hierarchy." },
        { title: "Motion", value: "Cubic Bézier Motion", desc: "Smooth interaction curves inspired by premium operating systems." },
        { title: "Spacing", value: "8pt Adaptive Grid", desc: "Consistent spacing rhythm optimized across responsive breakpoints." },
        { title: "Elevation", value: "Volumetric Depth", desc: "Layered blur, glow and surface hierarchy for physical interface feel." },
      ],
    },
    final: {
      badge: "Final Showcase // Production Grade",
      titleLine1: "Built for",
      titleLine2: "people who",
      titleLine3: "truly listen.",
      description: "A cinematic local-first music experience engineered with immersive motion, scalable architecture and high-fidelity performance.",
      inquiry: "Technical Access & Inquiry",
      modalLabel: "Music Player demo slideshow",
      slides: [
        { title: "Adaptive Aesthetic Engine", description: "Real-time look-and-feel switching utilizing a deeply decoupled token architecture for fluid runtime style mutations." },
        { title: "High-Fidelity Discovery Hub", description: "The core dashboard engineered for low-latency indexing, instant local asset ingestion, and structured data layout rendering." },
        { title: "Custom Accent Manifestation", description: "Demonstrating encapsulated component architecture where complex color spaces transition seamlessly without triggering expensive repaints." },
        { title: "Ergonomic Spatial Navigation", description: "A hardware-accelerated sidebar overlay designed with fine-tuned layout transitions to preserve the user's spatial focus." },
        { title: "Choreographed Playback Core", description: "The primary playback engine interface, mapping high-frequency audio spectrum updates to immersive visual micro-interactions." },
        { title: "Temporal Thread Termination", description: "Intelligent background lifecycle scheduling that fades audio output smoothly using precise, low-overhead system timer hooks." },
        { title: "Reactive Collection Matrix", description: "Highly optimized list rendering featuring rapid metadata caching, virtualized scrolling, and fluid collection transitions." },
        { title: "Algorithmic Curation Layer", description: "A personalized gateway that evaluates user playback metrics to dynamically generate reactive collections with local-first availability." },
        { title: "Zero-Latency Gapless Pipeline", description: "Under-the-hood audio scheduling that pre-buffers sequential tracks to achieve sample-accurate, zero-gap audio transitions." },
        { title: "Hardware-Accelerated DSP Matrix", description: "A multi-band parametric equalizer manipulating audio frequency nodes via low-level Digital Signal Processing threads." },
        { title: "In-Memory State Mutation", description: "Transactional local database insertion providing immediate, optimistic rendering updates when generating custom audio schemas." },
        { title: "Unified Audio Ecosystem", description: "The complete production-grade architectural overview, harmonizing local asset ingestion with clean, cinematic interface movements." },
        { title: "Variable Playback Rate Controller", description: "Micro-stepped speed modulation optimized for real-time audio time-stretching without distorting natural pitch frequencies." },
        { title: "Contextual Audio Overlays", description: "Deeply embedded slide-out interactions allowing advanced audio routing and spatial playback controls within the active player layer." },
      ],
    },
  },
  pt: {
    hero: {
      badge: "Estudo de Caso // Music Player",
      titleLine1: "Projetado",
      titleLine2: "para uma escuta",
      titleLine3: "imersiva.",
      description: "Uma experiência musical premium local-first, criada com motion cinematográfico, renderização de alta performance e design de interface imersivo.",
    },
    device: {
      badge: "Experiência do Produto",
      titleLine1: "Feito para parecer",
      titleAccent: "vivo.",
      description: "Projetado como um ecossistema musical premium focado em músicas do dispositivo, com interações imersivas, renderização fluida e movimentos cinematográficos de interface.",
      initializing: "Inicializando",
      standby: "Ecossistema_Em_Espera",
    },
    story: {
      chapter: "Capítulo",
      steps: [
        { tag: "Entrada / Experiência", title: "Arquitetura do Hub Inicial", desc: "A tela inicial define o tom com contextos inteligentes e cards tridimensionais responsivos." },
        { tag: "Sistema / Navegação", title: "Menu Lateral de Alta Fidelidade", desc: "Um painel lateral pensado para controle absoluto, equalização avançada e navegação precisa." },
        { tag: "Ecossistema / Customização", title: "Minimalismo Funcional", desc: "Uma jornada de playlists desenhada para reduzir carga cognitiva com espaço negativo estratégico." },
        { tag: "Interações / Modais", title: "Microinterações Fluidas", desc: "Modais suaves com profundidade visual e desfoques gaussianos cinematográficos." },
        { tag: "Curadoria / Playlists", title: "Gerenciamento Avançado", desc: "Organização modular de bibliotecas locais com feedback instantâneo e metadados dinâmicos." },
        { tag: "Imersão / Motor de Áudio", title: "Player Coreográfico e Funcional", desc: "Gradientes volumétricos vivos e iluminação reativa sincronizada com a atmosfera sonora." },
      ],
    },
    audio: {
      badge: "Imersão de Áudio",
      titleLine1: "Sinta cada",
      titleLine2: "frequência.",
      description: "Um motor de áudio cinematográfico criado para transformar a escuta offline em uma experiência sensorial imersiva com visuais reativos.",
    },
    performance: {
      badge: "Engenharia de Performance",
      titleLine1: "Feito para",
      titleLine2: "velocidade.",
      description: "Cada pipeline de renderização, camada de animação e interação de playback foi projetado para fluidez em alta taxa de atualização e estabilidade de produção.",
      metrics: [
        { value: "< 1.8s", label: "Inicialização Fria", desc: "Abertura ultrarrápida otimizada para dispositivos intermediários." },
        { value: "120 FPS", label: "Renderização Fluida", desc: "Motion cinematográfico estável com quedas mínimas de frames." },
        { value: "99.5%", label: "Sessões Sem Crash", desc: "Confiabilidade de produção e estabilidade em runtime." },
        { value: "JANK <1%", label: "Estabilidade Visual", desc: "Pipeline de rebuild e animação cuidadosamente otimizado." },
      ],
    },
    architecture: {
      badge: "Arquitetura do Sistema",
      titleLine1: "Engenharia",
      titleLine2: "para escala.",
      description: "Uma arquitetura modular de áudio desenhada para estabilidade, performance de renderização e orquestração escalável de playback entre plataformas.",
      nodeDescription: "Camada de orquestração otimizada para renderização de áudio premium.",
      active: "Ativo",
      items: ["Motor de Playback", "Sessão de Áudio", "Controlador de Fila", "Pipeline de Capas", "Camada de Cache", "Renderização de UI"],
    },
    design: {
      badge: "Design System",
      titleLine1: "Consistência",
      titleLine2: "em escala.",
      description: "Um sistema de interface coeso, criado com espaçamento adaptativo, motion cinematográfico e hierarquia visual escalável entre plataformas.",
      typographyScale: "Escala Tipográfica",
      display: "Display",
      cinematicHierarchy: "Hierarquia cinematográfica",
      typographyDescription: "Sistema tipográfico cuidadosamente balanceado para legibilidade, ritmo e composição visual imersiva.",
      tokens: [
        { title: "Tipografia", value: "Display / Editorial", desc: "Tipografia cinematográfica em grande escala para uma hierarquia imersiva." },
        { title: "Motion", value: "Movimento Cubic Bézier", desc: "Curvas de interação suaves inspiradas em sistemas operacionais premium." },
        { title: "Espaçamento", value: "Grid Adaptativo 8pt", desc: "Ritmo consistente de espaçamento otimizado para breakpoints responsivos." },
        { title: "Elevação", value: "Profundidade Volumétrica", desc: "Camadas de blur, glow e superfícies para uma sensação física de interface." },
      ],
    },
    final: {
      badge: "Showcase Final // Production Grade",
      titleLine1: "Feito para",
      titleLine2: "pessoas que",
      titleLine3: "realmente escutam.",
      description: "Uma experiência musical cinematográfica local-first, construída com motion imersivo, arquitetura escalável e performance de alta fidelidade.",
      inquiry: "Acesso Técnico & Conversa",
      modalLabel: "Apresentação demo do Music Player",
      slides: [
        { title: "Motor Estético Adaptativo", description: "Troca visual em tempo real usando uma arquitetura de tokens profundamente desacoplada para mutações fluidas em runtime." },
        { title: "Hub de Descoberta de Alta Fidelidade", description: "Dashboard central projetado para indexação de baixa latência, ingestão instantânea de assets locais e layout estruturado de dados." },
        { title: "Manifestação de Acento Personalizado", description: "Arquitetura de componentes encapsulada onde espaços complexos de cor transitam sem repaints caros." },
        { title: "Navegação Espacial Ergonômica", description: "Overlay lateral acelerado por hardware com transições ajustadas para preservar o foco espacial do usuário." },
        { title: "Core de Playback Coreografado", description: "Interface principal do player, conectando atualizações frequentes de espectro de áudio a microinterações imersivas." },
        { title: "Encerramento Temporal Inteligente", description: "Agendamento de ciclo de vida em background que reduz o áudio suavemente com timers precisos e leves." },
        { title: "Matriz Reativa de Coleções", description: "Renderização de listas altamente otimizada com cache rápido de metadados, rolagem virtualizada e transições fluidas." },
        { title: "Camada de Curadoria Algorítmica", description: "Gateway personalizado que avalia métricas de reprodução para gerar coleções reativas com disponibilidade local-first." },
        { title: "Pipeline Gapless de Latência Zero", description: "Agendamento de áudio que pré-carrega faixas sequenciais para transições sem intervalo e precisão de amostra." },
        { title: "Matriz DSP Acelerada por Hardware", description: "Equalizador paramétrico multibanda manipulando nós de frequência por threads de processamento de sinal digital." },
        { title: "Mutação de Estado em Memória", description: "Inserção transacional em banco local com updates otimistas imediatos ao gerar esquemas personalizados de áudio." },
        { title: "Ecossistema de Áudio Unificado", description: "Visão arquitetural production-grade unindo ingestão local de assets com movimentos de interface limpos e cinematográficos." },
        { title: "Controle de Velocidade Variável", description: "Modulação de velocidade em microetapas, otimizada para time-stretching em tempo real sem distorcer o pitch natural." },
        { title: "Overlays Contextuais de Áudio", description: "Interações slide-out profundas para roteamento avançado e controles espaciais dentro da camada ativa do player." },
      ],
    },
  },
  es: {
    hero: {
      badge: "Caso de Estudio // Music Player",
      titleLine1: "Diseñado",
      titleLine2: "para una escucha",
      titleLine3: "inmersiva.",
      description: "Una experiencia musical premium local-first, creada con motion cinematográfico, renderizado de alto rendimiento y diseño de interfaz inmersivo.",
    },
    device: {
      badge: "Experiencia del Producto",
      titleLine1: "Creado para sentirse",
      titleAccent: "vivo.",
      description: "Diseñado como un ecosistema musical premium enfocado en música del dispositivo, con interacciones inmersivas, renderizado fluido y movimientos cinematográficos de interfaz.",
      initializing: "Inicializando",
      standby: "Ecosistema_En_Espera",
    },
    story: {
      chapter: "Capítulo",
      steps: [
        { tag: "Entrada / Experiencia", title: "Arquitectura del Hub Inicial", desc: "La pantalla inicial marca el tono con contextos inteligentes y tarjetas tridimensionales responsivas." },
        { tag: "Sistema / Navegación", title: "Menú Lateral de Alta Fidelidad", desc: "Un panel lateral diseñado para control absoluto, ecualización avanzada y navegación precisa." },
        { tag: "Ecosistema / Personalización", title: "Minimalismo Funcional", desc: "Una experiencia de playlists diseñada para reducir carga cognitiva mediante espacio negativo estratégico." },
        { tag: "Interacciones / Modales", title: "Microinteracciones Fluidas", desc: "Modales suaves con profundidad visual y desenfoques gaussianos cinematográficos." },
        { tag: "Curaduría / Playlists", title: "Gestión Avanzada", desc: "Organización modular de bibliotecas locales con feedback instantáneo y metadatos dinámicos." },
        { tag: "Inmersión / Motor de Audio", title: "Player Coreográfico y Funcional", desc: "Gradientes volumétricos vivos e iluminación reactiva sincronizada con la atmósfera sonora." },
      ],
    },
    audio: {
      badge: "Inmersión de Audio",
      titleLine1: "Siente cada",
      titleLine2: "frecuencia.",
      description: "Un motor de audio cinematográfico creado para transformar la escucha offline en una experiencia sensorial inmersiva con visuales reactivos.",
    },
    performance: {
      badge: "Ingeniería de Rendimiento",
      titleLine1: "Creado para",
      titleLine2: "velocidad.",
      description: "Cada pipeline de renderizado, capa de animación e interacción de playback fue diseñado para fluidez en altas tasas de refresco y estabilidad de producción.",
      metrics: [
        { value: "< 1.8s", label: "Arranque en Frío", desc: "Inicio ultrarrápido optimizado para dispositivos de gama media." },
        { value: "120 FPS", label: "Renderizado Fluido", desc: "Motion cinematográfico estable con caídas mínimas de frames." },
        { value: "99.5%", label: "Sesiones Sin Crash", desc: "Confiabilidad de producción y estabilidad en runtime." },
        { value: "JANK <1%", label: "Estabilidad Visual", desc: "Pipeline de rebuild y animación cuidadosamente optimizado." },
      ],
    },
    architecture: {
      badge: "Arquitectura del Sistema",
      titleLine1: "Ingeniería",
      titleLine2: "para escalar.",
      description: "Una arquitectura modular de audio diseñada para estabilidad, rendimiento de renderizado y orquestación escalable de playback entre plataformas.",
      nodeDescription: "Capa de orquestación optimizada para renderizado de audio premium.",
      active: "Activo",
      items: ["Motor de Playback", "Sesión de Audio", "Controlador de Cola", "Pipeline de Portadas", "Capa de Caché", "Renderizado de UI"],
    },
    design: {
      badge: "Design System",
      titleLine1: "Consistencia",
      titleLine2: "a escala.",
      description: "Un sistema de interfaz cohesivo, diseñado con espaciado adaptativo, motion cinematográfico y jerarquía visual escalable entre plataformas.",
      typographyScale: "Escala Tipográfica",
      display: "Display",
      cinematicHierarchy: "Jerarquía cinematográfica",
      typographyDescription: "Sistema tipográfico cuidadosamente equilibrado para legibilidad, ritmo y composición visual inmersiva.",
      tokens: [
        { title: "Tipografía", value: "Display / Editorial", desc: "Tipografía cinematográfica de gran escala para una jerarquía inmersiva." },
        { title: "Motion", value: "Movimiento Cubic Bézier", desc: "Curvas de interacción suaves inspiradas en sistemas operativos premium." },
        { title: "Espaciado", value: "Grid Adaptativo 8pt", desc: "Ritmo consistente de espaciado optimizado para breakpoints responsivos." },
        { title: "Elevación", value: "Profundidad Volumétrica", desc: "Capas de blur, glow y superficies para una sensación física de interfaz." },
      ],
    },
    final: {
      badge: "Showcase Final // Production Grade",
      titleLine1: "Creado para",
      titleLine2: "personas que",
      titleLine3: "realmente escuchan.",
      description: "Una experiencia musical cinematográfica local-first, construida con motion inmersivo, arquitectura escalable y rendimiento de alta fidelidad.",
      inquiry: "Acceso Técnico y Consulta",
      modalLabel: "Presentación demo de Music Player",
      slides: [
        { title: "Motor Estético Adaptativo", description: "Cambio visual en tiempo real usando una arquitectura de tokens profundamente desacoplada para mutaciones fluidas en runtime." },
        { title: "Hub de Descubrimiento de Alta Fidelidad", description: "Dashboard central diseñado para indexación de baja latencia, ingesta instantánea de assets locales y layout estructurado de datos." },
        { title: "Manifestación de Acento Personalizado", description: "Arquitectura de componentes encapsulada donde espacios complejos de color transicionan sin repaints costosos." },
        { title: "Navegación Espacial Ergonómica", description: "Overlay lateral acelerado por hardware con transiciones ajustadas para preservar el foco espacial del usuario." },
        { title: "Core de Playback Coreografiado", description: "Interfaz principal del player, conectando actualizaciones frecuentes del espectro de audio con microinteracciones inmersivas." },
        { title: "Cierre Temporal Inteligente", description: "Programación del ciclo de vida en background que desvanece el audio suavemente con timers precisos y ligeros." },
        { title: "Matriz Reactiva de Colecciones", description: "Renderizado de listas altamente optimizado con caché rápida de metadatos, scroll virtualizado y transiciones fluidas." },
        { title: "Capa de Curaduría Algorítmica", description: "Gateway personalizado que evalúa métricas de reproducción para generar colecciones reactivas con disponibilidad local-first." },
        { title: "Pipeline Gapless de Latencia Cero", description: "Programación de audio que precarga pistas secuenciales para transiciones sin intervalo y precisión de muestra." },
        { title: "Matriz DSP Acelerada por Hardware", description: "Ecualizador paramétrico multibanda manipulando nodos de frecuencia mediante threads de procesamiento digital de señal." },
        { title: "Mutación de Estado en Memoria", description: "Inserción transaccional en base local con updates optimistas inmediatos al generar esquemas personalizados de audio." },
        { title: "Ecosistema de Audio Unificado", description: "Visión arquitectural production-grade que une ingesta local de assets con movimientos de interfaz limpios y cinematográficos." },
        { title: "Control de Velocidad Variable", description: "Modulación de velocidad en microetapas, optimizada para time-stretching en tiempo real sin distorsionar el pitch natural." },
        { title: "Overlays Contextuales de Audio", description: "Interacciones slide-out profundas para ruteo avanzado y controles espaciales dentro de la capa activa del player." },
      ],
    },
  },
} as const;
