export const musicPlayerContent = {
  en: {
    hero: {
      badge: "Case Study // Music Player",
      titleLine1: "Engineered",
      titleLine2: "for immersive",
      titleLine3: "listening.",
      description: "A local-first Flutter music player shaped around personal libraries, resilient playback state, native media controls and a polished listening experience.",
    },
    device: {
      badge: "Product Experience",
      titleLine1: "Built to feel",
      titleAccent: "alive.",
      description: "Designed for people who keep their own music library and expect playback, queue, playlists, widgets and imports to feel reliable across everyday use.",
      initializing: "Initializing",
      standby: "Ecosystem_Standby",
    },
    story: {
      chapter: "Chapter",
      steps: [
        {
          tag: "Gateway / Experience",
          title: "Initial Hub Architecture",
          desc: "The home screen introduces the library as the center of the product, surfacing local music, playlists and listening context without burying the user in controls.",
        },
        {
          tag: "System / Navigation",
          title: "High-Fidelity Side Menu",
          desc: "A side panel keeps playback tools, equalizer access and navigation close at hand while preserving focus on the current listening session.",
        },
        {
          tag: "Ecosystem / Customization",
          title: "Functional Minimalism",
          desc: "Playlist and collection flows were organized to make favorites, recents and most-played music easy to revisit.",
        },
        {
          tag: "Interactions / Modals",
          title: "Fluid Micro-Interactions",
          desc: "Dialogs and overlays support common actions without pulling the listener out of the playback flow.",
        },
        {
          tag: "Data Curation / Playlists",
          title: "Advanced Management",
          desc: "The local library is organized around SQLite persistence, metadata, playlists, favorites and restore-friendly state.",
        },
        {
          tag: "Immersion / Audio Engine",
          title: "The Choreographic and Functional Player",
          desc: "The player interface connects artwork, queue state and playback controls into a focused, expressive listening surface.",
        },
      ],
    },
    audio: {
      badge: "Audio Immersion",
      titleLine1: "Feel every",
      titleLine2: "frequency.",
      description: "The experience is built around local playback, background audio, queue restoration, gapless/crossfade options and native media controls where the platform supports them.",
    },
    performance: {
      badge: "Performance Engineering",
      titleLine1: "Built for",
      titleLine2: "speed.",
      description: "The project treats performance as release discipline: analyze, test, profile and document the behavior of the Home, Player, Queue and Scan flows before raising the bar.",
      metrics: [
        { value: "CI", label: "Release Checks", desc: "GitHub Actions runs Flutter analysis and tests as part of the hardening flow." },
        { value: "SQLite", label: "Local Library", desc: "Playlists, favorites, recents and queue state are organized around local persistence." },
        { value: "Lifecycle", label: "Safe Playback State", desc: "Queue, widgets and asynchronous listeners are treated as production-critical surfaces." },
        { value: "Profiling", label: "Performance Baselines", desc: "DevTools capture guides and release baselines shape the next optimization passes." },
      ],
    },
    architecture: {
      badge: "System Architecture",
      titleLine1: "Engineered",
      titleLine2: "for scale.",
      description: "A modular playback architecture separates UI, queue state, audio session handling, local storage, widgets and import flows so the app can evolve without hiding platform trade-offs.",
      nodeDescription: "Playback orchestration layer for local-first listening.",
      active: "Active",
      items: ["Playback Engine", "Audio Session", "Queue Controller", "Artwork Pipeline", "Cache Layer", "UI Rendering"],
    },
    design: {
      badge: "Design System",
      titleLine1: "Consistency",
      titleLine2: "at scale.",
      description: "A cohesive interface system designed with adaptive spacing, cinematic motion and scalable visual hierarchy across platforms.",
      typographyScale: "Typography Scale",
      display: "Display",
      cinematicHierarchy: "Cinematic hierarchy",
      typographyDescription: "Carefully balanced typography system designed for readability, rhythm and immersive visual composition.",
      tokens: [
        { title: "Typography", value: "Display / Editorial", desc: "Large-scale cinematic typography engineered for immersive hierarchy." },
        { title: "Motion", value: "Cubic Bézier Motion", desc: "Smooth interaction curves inspired by premium operating systems." },
        { title: "Spacing", value: "8pt Adaptive Grid", desc: "Consistent spacing rhythm optimized across responsive breakpoints." },
        { title: "Elevation", value: "Volumetric Depth", desc: "Layered blur, glow and surface hierarchy for physical interface feel." },
      ],
    },
    final: {
      badge: "Final Showcase // Production Grade",
      titleLine1: "Built for",
      titleLine2: "people who",
      titleLine3: "truly listen.",
      description: "A local-first music experience built for listeners who value ownership, reliable playback, careful platform integration and a product that does not pretend to know more about the audio path than it can actually observe.",
      inquiry: "Technical Access & Inquiry",
      modalLabel: "Music Player demo slideshow",
      slides: [
        { title: "Adaptive Aesthetic Engine", description: "Theme and surface choices give the player a distinct identity without separating style from usability." },
        { title: "High-Fidelity Discovery Hub", description: "The dashboard frames local music as the product center, with library entry points that stay close to real listening habits." },
        { title: "Custom Accent Manifestation", description: "Accent customization helps the interface feel personal while keeping the component system predictable." },
        { title: "Ergonomic Spatial Navigation", description: "The sidebar keeps navigation, playback tools and library actions reachable without breaking spatial focus." },
        { title: "Choreographed Playback Core", description: "The playback screen brings controls, artwork and queue context together in one calm, expressive surface." },
        { title: "Temporal Thread Termination", description: "Sleep timer and background behavior are treated as lifecycle features, not decorative extras." },
        { title: "Reactive Collection Matrix", description: "Collection screens organize local metadata, favorites, recents and playlists into repeatable listening flows." },
        { title: "Algorithmic Curation Layer", description: "Listening history and local availability shape the way collections can become more useful over time." },
        { title: "Zero-Latency Gapless Pipeline", description: "Gapless playback is presented as a platform-dependent capability that belongs in the real playback pipeline, not in marketing copy." },
        { title: "Hardware-Accelerated DSP Matrix", description: "Equalizer presets and output profiles give listeners control while keeping DSP behavior explicit." },
        { title: "In-Memory State Mutation", description: "Local persistence keeps library changes, playlists and preferences close to the device." },
        { title: "Unified Audio Ecosystem", description: "The full experience connects library ownership, playback reliability, native widgets and careful interface motion." },
        { title: "Variable Playback Rate Controller", description: "Playback speed controls support flexible listening while remaining part of the normal player surface." },
        { title: "Contextual Audio Overlays", description: "Contextual overlays keep advanced controls available without crowding the active playback layer." },
      ],
    },
  },
  pt: {
    hero: {
      badge: "Estudo de Caso // Music Player",
      titleLine1: "Projetado",
      titleLine2: "para uma escuta",
      titleLine3: "imersiva.",
      description: "Um player Flutter local-first criado para bibliotecas pessoais, estado de reproducao resiliente, controles nativos de midia e uma experiencia de escuta polida.",
    },
    device: {
      badge: "Experiência do Produto",
      titleLine1: "Feito para parecer",
      titleAccent: "vivo.",
      description: "Projetado como um ecossistema musical premium focado em músicas do dispositivo, com interações imersivas, renderização fluida e movimentos cinematográficos de interface.",
      initializing: "Inicializando",
      standby: "Ecossistema_Em_Espera",
    },
    story: {
      chapter: "Capítulo",
      steps: [
        { tag: "Entrada / Experiência", title: "Arquitetura do Hub Inicial", desc: "A tela inicial define o tom com contextos inteligentes e cards tridimensionais responsivos." },
        { tag: "Sistema / Navegação", title: "Menu Lateral de Alta Fidelidade", desc: "Um painel lateral pensado para controle absoluto, equalização avançada e navegação precisa." },
        { tag: "Ecossistema / Customização", title: "Minimalismo Funcional", desc: "Uma jornada de playlists desenhada para reduzir carga cognitiva com espaço negativo estratégico." },
        { tag: "Interações / Modais", title: "Microinterações Fluidas", desc: "Modais suaves com profundidade visual e desfoques gaussianos cinematográficos." },
        { tag: "Curadoria / Playlists", title: "Gerenciamento Avançado", desc: "Organização modular de bibliotecas locais com feedback instantâneo e metadados dinâmicos." },
        { tag: "Imersão / Motor de Áudio", title: "Player Coreográfico e Funcional", desc: "Gradientes volumétricos vivos e iluminação reativa sincronizada com a atmosfera sonora." },
      ],
    },
    audio: {
      badge: "Imersão de Áudio",
      titleLine1: "Sinta cada",
      titleLine2: "frequência.",
      description: "Um motor de áudio cinematográfico criado para transformar a escuta offline em uma experiência sensorial imersiva com visuais reativos.",
    },
    performance: {
      badge: "Engenharia de Performance",
      titleLine1: "Feito para",
      titleLine2: "velocidade.",
      description: "Cada pipeline de renderização, camada de animação e interação de playback foi projetado para fluidez em alta taxa de atualização e estabilidade de produção.",
      metrics: [
        { value: "CI", label: "Release Checks", desc: "Analysis and automated tests guide the hardening flow." },
        { value: "SQLite", label: "Local Library", desc: "Playlists, favorites, recents and queue state are organized around local persistence." },
        { value: "Lifecycle", label: "Safe State", desc: "Queue, widgets and async listeners are treated as critical playback surfaces." },
        { value: "Profiling", label: "Performance Baselines", desc: "DevTools capture guides shape the next optimization passes." },
      ],
    },
    architecture: {
      badge: "Arquitetura do Sistema",
      titleLine1: "Engenharia",
      titleLine2: "para escala.",
      description: "Uma arquitetura modular de áudio desenhada para estabilidade, performance de renderização e orquestração escalável de playback entre plataformas.",
      nodeDescription: "Camada de orquestração otimizada para renderização de áudio premium.",
      active: "Ativo",
      items: ["Motor de Playback", "Sessão de Áudio", "Controlador de Fila", "Pipeline de Capas", "Camada de Cache", "Renderização de UI"],
    },
    design: {
      badge: "Design System",
      titleLine1: "Consistência",
      titleLine2: "em escala.",
      description: "Um sistema de interface coeso, criado com espaçamento adaptativo, motion cinematográfico e hierarquia visual escalável entre plataformas.",
      typographyScale: "Escala Tipográfica",
      display: "Display",
      cinematicHierarchy: "Hierarquia cinematográfica",
      typographyDescription: "Sistema tipográfico cuidadosamente balanceado para legibilidade, ritmo e composição visual imersiva.",
      tokens: [
        { title: "Tipografia", value: "Display / Editorial", desc: "Tipografia cinematográfica em grande escala para uma hierarquia imersiva." },
        { title: "Motion", value: "Movimento Cubic Bézier", desc: "Curvas de interação suaves inspiradas em sistemas operacionais premium." },
        { title: "Espaçamento", value: "Grid Adaptativo 8pt", desc: "Ritmo consistente de espaçamento otimizado para breakpoints responsivos." },
        { title: "Elevação", value: "Profundidade Volumétrica", desc: "Camadas de blur, glow e superfícies para uma sensação física de interface." },
      ],
    },
    final: {
      badge: "Showcase Final // Production Grade",
      titleLine1: "Feito para",
      titleLine2: "pessoas que",
      titleLine3: "realmente escutam.",
      description: "Uma experiência musical cinematográfica local-first, construída com motion imersivo, arquitetura escalável e performance de alta fidelidade.",
      inquiry: "Acesso Técnico & Conversa",
      modalLabel: "Apresentação demo do Music Player",
      slides: [
        { title: "Motor Estético Adaptativo", description: "Troca visual em tempo real usando uma arquitetura de tokens profundamente desacoplada para mutações fluidas em runtime." },
        { title: "Hub de Descoberta de Alta Fidelidade", description: "Dashboard central projetado para indexação de baixa latência, ingestão instantânea de assets locais e layout estruturado de dados." },
        { title: "Manifestação de Acento Personalizado", description: "Arquitetura de componentes encapsulada onde espaços complexos de cor transitam sem repaints caros." },
        { title: "Navegação Espacial Ergonômica", description: "Overlay lateral acelerado por hardware com transições ajustadas para preservar o foco espacial do usuário." },
        { title: "Core de Playback Coreografado", description: "Interface principal do player, conectando atualizações frequentes de espectro de áudio a microinterações imersivas." },
        { title: "Encerramento Temporal Inteligente", description: "Agendamento de ciclo de vida em background que reduz o áudio suavemente com timers precisos e leves." },
        { title: "Matriz Reativa de Coleções", description: "Renderização de listas altamente otimizada com cache rápido de metadados, rolagem virtualizada e transições fluidas." },
        { title: "Camada de Curadoria Algorítmica", description: "Gateway personalizado que avalia métricas de reprodução para gerar coleções reativas com disponibilidade local-first." },
        { title: "Pipeline Gapless de Latência Zero", description: "Agendamento de áudio que pré-carrega faixas sequenciais para transições sem intervalo e precisão de amostra." },
        { title: "Matriz DSP Acelerada por Hardware", description: "Equalizador paramétrico multibanda manipulando nós de frequência por threads de processamento de sinal digital." },
        { title: "Mutação de Estado em Memória", description: "Inserção transacional em banco local com updates otimistas imediatos ao gerar esquemas personalizados de áudio." },
        { title: "Ecossistema de Áudio Unificado", description: "Visão arquitetural production-grade unindo ingestão local de assets com movimentos de interface limpos e cinematográficos." },
        { title: "Controle de Velocidade Variável", description: "Modulação de velocidade em microetapas, otimizada para time-stretching em tempo real sem distorcer o pitch natural." },
        { title: "Overlays Contextuais de Áudio", description: "Interações slide-out profundas para roteamento avançado e controles espaciais dentro da camada ativa do player." },
      ],
    },
  },
  es: {
    hero: {
      badge: "Caso de Estudio // Music Player",
      titleLine1: "Diseñado",
      titleLine2: "para una escucha",
      titleLine3: "inmersiva.",
      description: "Una experiencia musical premium local-first, creada con motion cinematográfico, renderizado de alto rendimiento y diseño de interfaz inmersivo.",
    },
    device: {
      badge: "Experiencia del Producto",
      titleLine1: "Creado para sentirse",
      titleAccent: "vivo.",
      description: "Diseñado como un ecosistema musical premium enfocado en música del dispositivo, con interacciones inmersivas, renderizado fluido y movimientos cinematográficos de interfaz.",
      initializing: "Inicializando",
      standby: "Ecosistema_En_Espera",
    },
    story: {
      chapter: "Capítulo",
      steps: [
        { tag: "Entrada / Experiencia", title: "Arquitectura del Hub Inicial", desc: "La pantalla inicial marca el tono con contextos inteligentes y tarjetas tridimensionales responsivas." },
        { tag: "Sistema / Navegación", title: "Menú Lateral de Alta Fidelidad", desc: "Un panel lateral diseñado para control absoluto, ecualización avanzada y navegación precisa." },
        { tag: "Ecosistema / Personalización", title: "Minimalismo Funcional", desc: "Una experiencia de playlists diseñada para reducir carga cognitiva mediante espacio negativo estratégico." },
        { tag: "Interacciones / Modales", title: "Microinteracciones Fluidas", desc: "Modales suaves con profundidad visual y desenfoques gaussianos cinematográficos." },
        { tag: "Curaduría / Playlists", title: "Gestión Avanzada", desc: "Organización modular de bibliotecas locales con feedback instantáneo y metadatos dinámicos." },
        { tag: "Inmersión / Motor de Audio", title: "Player Coreográfico y Funcional", desc: "Gradientes volumétricos vivos e iluminación reactiva sincronizada con la atmósfera sonora." },
      ],
    },
    audio: {
      badge: "Inmersión de Audio",
      titleLine1: "Siente cada",
      titleLine2: "frecuencia.",
      description: "Un motor de audio cinematográfico creado para transformar la escucha offline en una experiencia sensorial inmersiva con visuales reactivos.",
    },
    performance: {
      badge: "Ingeniería de Rendimiento",
      titleLine1: "Creado para",
      titleLine2: "velocidad.",
      description: "Cada pipeline de renderizado, capa de animación e interacción de playback fue diseñado para fluidez en altas tasas de refresco y estabilidad de producción.",
      metrics: [
        { value: "CI", label: "Release Checks", desc: "Analysis and automated tests guide the hardening flow." },
        { value: "SQLite", label: "Local Library", desc: "Playlists, favorites, recents and queue state are organized around local persistence." },
        { value: "Lifecycle", label: "Safe State", desc: "Queue, widgets and async listeners are treated as critical playback surfaces." },
        { value: "Profiling", label: "Performance Baselines", desc: "DevTools capture guides shape the next optimization passes." },
      ],
    },
    architecture: {
      badge: "Arquitectura del Sistema",
      titleLine1: "Ingeniería",
      titleLine2: "para escalar.",
      description: "Una arquitectura modular de audio diseñada para estabilidad, rendimiento de renderizado y orquestación escalable de playback entre plataformas.",
      nodeDescription: "Capa de orquestación optimizada para renderizado de audio premium.",
      active: "Activo",
      items: ["Motor de Playback", "Sesión de Audio", "Controlador de Cola", "Pipeline de Portadas", "Capa de Caché", "Renderizado de UI"],
    },
    design: {
      badge: "Design System",
      titleLine1: "Consistencia",
      titleLine2: "a escala.",
      description: "Un sistema de interfaz cohesivo, diseñado con espaciado adaptativo, motion cinematográfico y jerarquía visual escalable entre plataformas.",
      typographyScale: "Escala Tipográfica",
      display: "Display",
      cinematicHierarchy: "Jerarquía cinematográfica",
      typographyDescription: "Sistema tipográfico cuidadosamente equilibrado para legibilidad, ritmo y composición visual inmersiva.",
      tokens: [
        { title: "Tipografía", value: "Display / Editorial", desc: "Tipografía cinematográfica de gran escala para una jerarquía inmersiva." },
        { title: "Motion", value: "Movimiento Cubic Bézier", desc: "Curvas de interacción suaves inspiradas en sistemas operativos premium." },
        { title: "Espaciado", value: "Grid Adaptativo 8pt", desc: "Ritmo consistente de espaciado optimizado para breakpoints responsivos." },
        { title: "Elevación", value: "Profundidad Volumétrica", desc: "Capas de blur, glow y superficies para una sensación física de interfaz." },
      ],
    },
    final: {
      badge: "Showcase Final // Production Grade",
      titleLine1: "Creado para",
      titleLine2: "personas que",
      titleLine3: "realmente escuchan.",
      description: "Una experiencia musical cinematográfica local-first, construida con motion inmersivo, arquitectura escalable y rendimiento de alta fidelidad.",
      inquiry: "Acceso Técnico y Consulta",
      modalLabel: "Presentación demo de Music Player",
      slides: [
        { title: "Motor Estético Adaptativo", description: "Cambio visual en tiempo real usando una arquitectura de tokens profundamente desacoplada para mutaciones fluidas en runtime." },
        { title: "Hub de Descubrimiento de Alta Fidelidad", description: "Dashboard central diseñado para indexación de baja latencia, ingesta instantánea de assets locales y layout estructurado de datos." },
        { title: "Manifestación de Acento Personalizado", description: "Arquitectura de componentes encapsulada donde espacios complejos de color transicionan sin repaints costosos." },
        { title: "Navegación Espacial Ergonómica", description: "Overlay lateral acelerado por hardware con transiciones ajustadas para preservar el foco espacial del usuario." },
        { title: "Core de Playback Coreografiado", description: "Interfaz principal del player, conectando actualizaciones frecuentes del espectro de audio con microinteracciones inmersivas." },
        { title: "Cierre Temporal Inteligente", description: "Programación del ciclo de vida en background que desvanece el audio suavemente con timers precisos y ligeros." },
        { title: "Matriz Reactiva de Colecciones", description: "Renderizado de listas altamente optimizado con caché rápida de metadatos, scroll virtualizado y transiciones fluidas." },
        { title: "Capa de Curaduría Algorítmica", description: "Gateway personalizado que evalúa métricas de reproducción para generar colecciones reactivas con disponibilidad local-first." },
        { title: "Pipeline Gapless de Latencia Cero", description: "Programación de audio que precarga pistas secuenciales para transiciones sin intervalo y precisión de muestra." },
        { title: "Matriz DSP Acelerada por Hardware", description: "Ecualizador paramétrico multibanda manipulando nodos de frecuencia mediante threads de procesamiento digital de señal." },
        { title: "Mutación de Estado en Memoria", description: "Inserción transaccional en base local con updates optimistas inmediatos al generar esquemas personalizados de audio." },
        { title: "Ecosistema de Audio Unificado", description: "Visión arquitectural production-grade que une ingesta local de assets con movimientos de interfaz limpios y cinematográficos." },
        { title: "Control de Velocidad Variable", description: "Modulación de velocidad en microetapas, optimizada para time-stretching en tiempo real sin distorsionar el pitch natural." },
        { title: "Overlays Contextuales de Audio", description: "Interacciones slide-out profundas para ruteo avanzado y controles espaciales dentro de la capa activa del player." },
      ],
    },
  },
} as const;
