export const musicPlayerContent = {
  en: {
    hero: {
      badge: "Case Study // Music Player",
      titleLine1: "Local-first",
      titleLine2: "listening,",
      titleLine3: "engineered.",
      description: "A Flutter music player shaped around personal libraries, resilient playback state, native media controls and a listening experience that stays honest about platform limits.",
    },
    device: {
      badge: "Problem",
      titleLine1: "Listening should feel",
      titleAccent: "owned.",
      description: "Many players hide the real playback path behind polished screens. This case starts from a practical question: how can a local music app keep library ownership, playback controls and everyday reliability visible to the listener?",
      initializing: "Initializing",
      standby: "Local_First_Standby",
    },
    story: {
      chapter: "Chapter",
      steps: [
        {
          tag: "Problem / Library",
          title: "The Library Is the Product Center",
          desc: "The home screen treats local music, playlists and listening context as the starting point instead of pushing the listener through remote discovery patterns.",
        },
        {
          tag: "Decision / Navigation",
          title: "Playback Tools Stay Close",
          desc: "The side menu keeps equalizer access, navigation and playback-adjacent actions reachable without taking attention away from the current session.",
        },
        {
          tag: "Solution / Collections",
          title: "Collections Stay Recoverable",
          desc: "Favorites, recents, playlists and local metadata are organized around flows that make personal libraries easier to revisit and maintain.",
        },
        {
          tag: "Solution / Interaction",
          title: "Overlays Support the Flow",
          desc: "Dialogs and contextual panels are used for focused actions so advanced controls do not crowd the primary playback surface.",
        },
        {
          tag: "Evidence / Persistence",
          title: "State Belongs Near the Device",
          desc: "SQLite-backed persistence is the anchor for playlists, preferences, recent activity and queue recovery in the local-first direction.",
        },
        {
          tag: "Result / Listening Surface",
          title: "A Focused Player Experience",
          desc: "The player screen brings artwork, queue context and transport controls together in a calm, expressive interface designed around real listening behavior.",
        },
      ],
    },
    audio: {
      badge: "Engineering Decision",
      titleLine1: "Control the",
      titleLine2: "playback path.",
      description: "The architecture prioritizes local playback, background audio, queue restoration and native media controls. Gapless, crossfade and output behavior are treated as platform-dependent capabilities that need direct validation before being promoted as guarantees.",
    },
    performance: {
      badge: "Evidence Plan",
      titleLine1: "Measure before",
      titleLine2: "claiming speed.",
      description: "Performance is framed as release discipline: analyze the Home, Player, Queue and Scan flows, capture profiling evidence, and only publish numbers once they can be reproduced.",
      metrics: [
        { value: "CI", label: "Release Checks", desc: "Automated analysis and tests are part of the hardening path before stronger public claims." },
        { value: "SQLite", label: "Local Library", desc: "Playlists, favorites, recents and queue state are organized around local persistence." },
        { value: "Lifecycle", label: "Safe Playback State", desc: "Queue, widgets, timers and asynchronous listeners are treated as production-critical surfaces." },
        { value: "Profiling", label: "Pending Baselines", desc: "DevTools or trace captures are required before publishing cold-start, FPS or audio-path claims." },
      ],
    },
    architecture: {
      badge: "Solution",
      titleLine1: "Modular by",
      titleLine2: "responsibility.",
      description: "The case is organized around separation of responsibilities: UI, queue state, audio session handling, local storage, artwork, widgets and import flows can evolve without being hidden behind one oversized player layer.",
      nodeDescription: "Playback responsibility in the local-first architecture.",
      active: "Active",
      items: ["Playback Engine", "Audio Session", "Queue Controller", "Artwork Pipeline", "Persistence Layer", "UI Rendering"],
    },
    design: {
      badge: "Product Language",
      titleLine1: "Interface with",
      titleLine2: "discipline.",
      description: "The visual direction stays immersive, but the case now separates design intent from measured claims. Motion, spacing and hierarchy support orientation instead of replacing technical evidence.",
      typographyScale: "Typography Scale",
      display: "Display",
      cinematicHierarchy: "Cinematic hierarchy",
      typographyDescription: "Typography is used to create hierarchy and rhythm while keeping the listening flow readable across screen sizes.",
      tokens: [
        { title: "Typography", value: "Display / Editorial", desc: "Large titles create a cinematic case-study rhythm without carrying technical claims." },
        { title: "Motion", value: "Guided Motion", desc: "Animation is used to guide attention and should remain compatible with reduced-motion expectations." },
        { title: "Spacing", value: "Adaptive Grid", desc: "Responsive spacing keeps playback surfaces, cards and controls readable." },
        { title: "Elevation", value: "Layered Surfaces", desc: "Depth, blur and glow support the product mood while keeping controls distinguishable." },
      ],
    },
    final: {
      badge: "Result // Local-First Music Case",
      titleLine1: "Built for",
      titleLine2: "people who",
      titleLine3: "keep listening.",
      description: "A local-first music experience for listeners who value library ownership, reliable playback flows, careful platform integration and product language that does not promise more than the audio path can prove.",
      inquiry: "Technical Access & Inquiry",
      modalLabel: "Music Player demo slideshow",
      slides: [
        { title: "Adaptive Visual Identity", description: "Themes and surfaces give the player a distinct identity while keeping style connected to usability." },
        { title: "Local Discovery Hub", description: "The dashboard frames local music as the product center, with entry points close to everyday listening habits." },
        { title: "Custom Accent System", description: "Accent choices make the interface feel personal while keeping component behavior predictable." },
        { title: "Spatial Navigation", description: "The sidebar keeps navigation, playback tools and library actions reachable without breaking focus." },
        { title: "Playback Core", description: "The player surface brings controls, artwork and queue context together in one calm interface." },
        { title: "Sleep Timer Flow", description: "Timer and background behavior are treated as lifecycle features, not decorative extras." },
        { title: "Collection Matrix", description: "Collection screens organize local metadata, favorites, recents and playlists into repeatable flows." },
        { title: "Curation Direction", description: "Listening history and local availability can shape how collections become more useful over time." },
        { title: "Gapless Direction", description: "Gapless playback is treated as a platform-dependent capability that requires validation in the real pipeline." },
        { title: "Equalizer Surface", description: "Equalizer presets and output controls give listeners more control while keeping DSP behavior explicit." },
        { title: "Local State", description: "Local persistence keeps library changes, playlists and preferences close to the device." },
        { title: "Unified Audio Experience", description: "The experience connects library ownership, playback reliability, native widgets and careful interface motion." },
        { title: "Playback Speed", description: "Speed controls support flexible listening while staying part of the normal player surface." },
        { title: "Contextual Controls", description: "Contextual overlays keep advanced controls available without crowding the active playback layer." },
      ],
    },
  },
  pt: {
    hero: {
      badge: "Estudo de Caso // Music Player",
      titleLine1: "Escuta",
      titleLine2: "local-first,",
      titleLine3: "projetada.",
      description: "Um player Flutter pensado para bibliotecas pessoais, estado de reprodução resiliente, controles nativos de mídia e uma experiência de escuta honesta sobre limites de plataforma.",
    },
    device: {
      badge: "Problema",
      titleLine1: "Escutar deve parecer",
      titleAccent: "seu.",
      description: "Muitos players escondem o caminho real de reprodução atrás de telas bonitas. Este case parte de uma pergunta prática: como um app local pode manter biblioteca, controles e confiabilidade cotidiana visíveis para quem escuta?",
      initializing: "Inicializando",
      standby: "Local_First_Em_Espera",
    },
    story: {
      chapter: "Capítulo",
      steps: [
        {
          tag: "Problema / Biblioteca",
          title: "A Biblioteca É o Centro do Produto",
          desc: "A tela inicial trata músicas locais, playlists e contexto de escuta como ponto de partida, sem empurrar a experiência para padrões de descoberta remota.",
        },
        {
          tag: "Decisão / Navegação",
          title: "Ferramentas de Playback Ficam Próximas",
          desc: "O menu lateral mantém equalizador, navegação e ações ligadas à reprodução acessíveis sem tirar atenção da sessão atual.",
        },
        {
          tag: "Solução / Coleções",
          title: "Coleções Continuam Recuperáveis",
          desc: "Favoritos, recentes, playlists e metadados locais são organizados em fluxos que facilitam revisitar e manter bibliotecas pessoais.",
        },
        {
          tag: "Solução / Interação",
          title: "Overlays Apoiam o Fluxo",
          desc: "Diálogos e painéis contextuais concentram ações específicas para que controles avançados não disputem espaço com a superfície principal do player.",
        },
        {
          tag: "Evidência / Persistência",
          title: "O Estado Fica Perto do Dispositivo",
          desc: "A persistência com SQLite é a âncora para playlists, preferências, atividade recente e recuperação de fila na direção local-first.",
        },
        {
          tag: "Resultado / Superfície de Escuta",
          title: "Uma Experiência de Player Focada",
          desc: "A tela de reprodução reúne capa, contexto de fila e controles em uma interface calma e expressiva, desenhada em torno do comportamento real de escuta.",
        },
      ],
    },
    audio: {
      badge: "Decisão de Engenharia",
      titleLine1: "Controlar o",
      titleLine2: "caminho do áudio.",
      description: "A arquitetura prioriza reprodução local, áudio em segundo plano, restauração de fila e controles nativos de mídia. Gapless, crossfade e comportamento de saída são tratados como capacidades dependentes da plataforma que precisam de validação direta antes de virarem garantias públicas.",
    },
    performance: {
      badge: "Plano de Evidência",
      titleLine1: "Medir antes de",
      titleLine2: "prometer velocidade.",
      description: "Performance entra como disciplina de release: analisar fluxos de Home, Player, Fila e Scan, capturar evidências de profiling e publicar números somente quando forem reproduzíveis.",
      metrics: [
        { value: "CI", label: "Checks de Release", desc: "Análise e testes automatizados fazem parte do caminho de endurecimento antes de claims públicos mais fortes." },
        { value: "SQLite", label: "Biblioteca Local", desc: "Playlists, favoritos, recentes e estado de fila são organizados em torno de persistência local." },
        { value: "Lifecycle", label: "Estado Seguro", desc: "Fila, widgets, timers e listeners assíncronos são tratados como superfícies críticas de reprodução." },
        { value: "Profiling", label: "Baselines Pendentes", desc: "Capturas por DevTools ou trace são necessárias antes de publicar cold start, FPS ou claims de caminho de áudio." },
      ],
    },
    architecture: {
      badge: "Solução",
      titleLine1: "Modular por",
      titleLine2: "responsabilidade.",
      description: "O case é organizado pela separação de responsabilidades: UI, estado de fila, sessão de áudio, armazenamento local, capas, widgets e fluxos de importação podem evoluir sem ficarem escondidos atrás de uma única camada gigante de player.",
      nodeDescription: "Responsabilidade de playback na arquitetura local-first.",
      active: "Ativo",
      items: ["Motor de Playback", "Sessão de Áudio", "Controlador de Fila", "Pipeline de Capas", "Camada de Persistência", "Renderização de UI"],
    },
    design: {
      badge: "Linguagem de Produto",
      titleLine1: "Interface com",
      titleLine2: "disciplina.",
      description: "A direção visual continua imersiva, mas o case agora separa intenção de design de claims medidos. Motion, espaçamento e hierarquia apoiam orientação sem substituir evidência técnica.",
      typographyScale: "Escala Tipográfica",
      display: "Display",
      cinematicHierarchy: "Hierarquia cinematográfica",
      typographyDescription: "A tipografia cria hierarquia e ritmo enquanto mantém o fluxo de escuta legível em diferentes tamanhos de tela.",
      tokens: [
        { title: "Tipografia", value: "Display / Editorial", desc: "Títulos grandes criam ritmo cinematográfico de case sem carregar claims técnicos." },
        { title: "Motion", value: "Movimento Guiado", desc: "Animação orienta atenção e deve continuar compatível com expectativas de reduced motion." },
        { title: "Espaçamento", value: "Grid Adaptativo", desc: "Espaçamento responsivo mantém superfícies, cards e controles legíveis." },
        { title: "Elevação", value: "Superfícies em Camadas", desc: "Profundidade, blur e glow sustentam o clima do produto sem perder distinção de controles." },
      ],
    },
    final: {
      badge: "Resultado // Case Musical Local-First",
      titleLine1: "Feito para",
      titleLine2: "quem continua",
      titleLine3: "escutando.",
      description: "Uma experiência musical local-first para ouvintes que valorizam posse da biblioteca, fluxos confiáveis de reprodução, integração cuidadosa com a plataforma e uma linguagem de produto que não promete mais do que o caminho de áudio pode provar.",
      inquiry: "Acesso Técnico & Conversa",
      modalLabel: "Apresentação demo do Music Player",
      slides: [
        { title: "Identidade Visual Adaptativa", description: "Temas e superfícies dão identidade ao player mantendo estilo conectado à usabilidade." },
        { title: "Hub de Descoberta Local", description: "O dashboard coloca músicas locais no centro do produto, com entradas próximas dos hábitos reais de escuta." },
        { title: "Sistema de Acento Personalizado", description: "Escolhas de acento tornam a interface mais pessoal sem quebrar a previsibilidade dos componentes." },
        { title: "Navegação Espacial", description: "A sidebar mantém navegação, ferramentas de playback e ações de biblioteca acessíveis sem quebrar o foco." },
        { title: "Núcleo de Reprodução", description: "A superfície do player reúne controles, capa e contexto de fila em uma interface calma." },
        { title: "Fluxo de Sleep Timer", description: "Timer e comportamento em segundo plano são tratados como recursos de lifecycle, não como extras decorativos." },
        { title: "Matriz de Coleções", description: "Telas de coleção organizam metadados locais, favoritos, recentes e playlists em fluxos repetíveis." },
        { title: "Direção de Curadoria", description: "Histórico de escuta e disponibilidade local podem tornar coleções mais úteis ao longo do tempo." },
        { title: "Direção Gapless", description: "Gapless é tratado como capacidade dependente da plataforma que exige validação no pipeline real." },
        { title: "Superfície de Equalizador", description: "Presets e controles de saída ampliam o controle do ouvinte mantendo o comportamento de DSP explícito." },
        { title: "Estado Local", description: "Persistência local mantém mudanças de biblioteca, playlists e preferências perto do dispositivo." },
        { title: "Experiência de Áudio Unificada", description: "A experiência conecta posse da biblioteca, confiabilidade de reprodução, widgets nativos e motion cuidadoso." },
        { title: "Velocidade de Reprodução", description: "Controles de velocidade apoiam escutas flexíveis dentro da superfície normal do player." },
        { title: "Controles Contextuais", description: "Overlays mantêm controles avançados disponíveis sem lotar a camada ativa de reprodução." },
      ],
    },
  },
  es: {
    hero: {
      badge: "Caso de Estudio // Music Player",
      titleLine1: "Escucha",
      titleLine2: "local-first,",
      titleLine3: "diseñada.",
      description: "Un reproductor Flutter pensado para bibliotecas personales, estado de reproducción resiliente, controles nativos de medios y una experiencia de escucha honesta sobre límites de plataforma.",
    },
    device: {
      badge: "Problema",
      titleLine1: "Escuchar debe sentirse",
      titleAccent: "propio.",
      description: "Muchos reproductores esconden el camino real de reproducción detrás de pantallas bonitas. Este caso parte de una pregunta práctica: ¿cómo puede una app local mantener biblioteca, controles y confiabilidad cotidiana visibles para quien escucha?",
      initializing: "Inicializando",
      standby: "Local_First_En_Espera",
    },
    story: {
      chapter: "Capítulo",
      steps: [
        {
          tag: "Problema / Biblioteca",
          title: "La Biblioteca Es el Centro del Producto",
          desc: "La pantalla inicial trata música local, playlists y contexto de escucha como punto de partida, sin empujar la experiencia hacia patrones de descubrimiento remoto.",
        },
        {
          tag: "Decisión / Navegación",
          title: "Herramientas de Playback Cerca",
          desc: "El menú lateral mantiene ecualizador, navegación y acciones cercanas a la reproducción accesibles sin quitar atención de la sesión actual.",
        },
        {
          tag: "Solución / Colecciones",
          title: "Colecciones Recuperables",
          desc: "Favoritos, recientes, playlists y metadatos locales se organizan en flujos que facilitan volver a bibliotecas personales y mantenerlas.",
        },
        {
          tag: "Solución / Interacción",
          title: "Overlays Que Apoyan el Flujo",
          desc: "Diálogos y paneles contextuales concentran acciones específicas para que los controles avanzados no compitan con la superficie principal del reproductor.",
        },
        {
          tag: "Evidencia / Persistencia",
          title: "El Estado Vive Cerca del Dispositivo",
          desc: "La persistencia con SQLite es el ancla para playlists, preferencias, actividad reciente y recuperación de cola en la dirección local-first.",
        },
        {
          tag: "Resultado / Superficie de Escucha",
          title: "Una Experiencia de Player Enfocada",
          desc: "La pantalla de reproducción reúne portada, contexto de cola y controles en una interfaz calma y expresiva, diseñada alrededor del comportamiento real de escucha.",
        },
      ],
    },
    audio: {
      badge: "Decisión de Ingeniería",
      titleLine1: "Controlar el",
      titleLine2: "camino del audio.",
      description: "La arquitectura prioriza reproducción local, audio en segundo plano, restauración de cola y controles nativos de medios. Gapless, crossfade y comportamiento de salida se tratan como capacidades dependientes de la plataforma que necesitan validación directa antes de convertirse en garantías públicas.",
    },
    performance: {
      badge: "Plan de Evidencia",
      titleLine1: "Medir antes de",
      titleLine2: "prometer velocidad.",
      description: "El rendimiento entra como disciplina de release: analizar flujos de Home, Player, Cola y Scan, capturar evidencias de profiling y publicar números solo cuando puedan reproducirse.",
      metrics: [
        { value: "CI", label: "Checks de Release", desc: "Análisis y tests automatizados forman parte del endurecimiento antes de claims públicos más fuertes." },
        { value: "SQLite", label: "Biblioteca Local", desc: "Playlists, favoritos, recientes y estado de cola se organizan alrededor de persistencia local." },
        { value: "Lifecycle", label: "Estado Seguro", desc: "Cola, widgets, timers y listeners asíncronos se tratan como superficies críticas de reproducción." },
        { value: "Profiling", label: "Baselines Pendientes", desc: "Capturas con DevTools o trace son necesarias antes de publicar cold start, FPS o claims sobre el camino de audio." },
      ],
    },
    architecture: {
      badge: "Solución",
      titleLine1: "Modular por",
      titleLine2: "responsabilidad.",
      description: "El caso se organiza por separación de responsabilidades: UI, estado de cola, sesión de audio, almacenamiento local, portadas, widgets y flujos de importación pueden evolucionar sin quedar escondidos detrás de una única capa gigante de player.",
      nodeDescription: "Responsabilidad de playback en la arquitectura local-first.",
      active: "Activo",
      items: ["Motor de Playback", "Sesión de Audio", "Controlador de Cola", "Pipeline de Portadas", "Capa de Persistencia", "Renderizado de UI"],
    },
    design: {
      badge: "Lenguaje de Producto",
      titleLine1: "Interfaz con",
      titleLine2: "disciplina.",
      description: "La dirección visual sigue siendo inmersiva, pero el caso ahora separa intención de diseño de claims medidos. Motion, espaciado y jerarquía apoyan orientación sin reemplazar evidencia técnica.",
      typographyScale: "Escala Tipográfica",
      display: "Display",
      cinematicHierarchy: "Jerarquía cinematográfica",
      typographyDescription: "La tipografía crea jerarquía y ritmo mientras mantiene el flujo de escucha legible en distintos tamaños de pantalla.",
      tokens: [
        { title: "Tipografía", value: "Display / Editorial", desc: "Títulos grandes crean ritmo cinematográfico de caso sin cargar claims técnicos." },
        { title: "Motion", value: "Movimiento Guiado", desc: "La animación orienta la atención y debe seguir compatible con expectativas de reduced motion." },
        { title: "Espaciado", value: "Grid Adaptativo", desc: "El espaciado responsivo mantiene superficies, cards y controles legibles." },
        { title: "Elevación", value: "Superficies en Capas", desc: "Profundidad, blur y glow sostienen el clima del producto sin perder distinción de controles." },
      ],
    },
    final: {
      badge: "Resultado // Caso Musical Local-First",
      titleLine1: "Creado para",
      titleLine2: "quienes siguen",
      titleLine3: "escuchando.",
      description: "Una experiencia musical local-first para oyentes que valoran posesión de biblioteca, flujos confiables de reproducción, integración cuidadosa con la plataforma y un lenguaje de producto que no promete más de lo que el camino de audio puede probar.",
      inquiry: "Acceso Técnico y Consulta",
      modalLabel: "Presentación demo de Music Player",
      slides: [
        { title: "Identidad Visual Adaptativa", description: "Temas y superficies dan identidad al reproductor manteniendo el estilo conectado a la usabilidad." },
        { title: "Hub de Descubrimiento Local", description: "El dashboard pone música local en el centro del producto, con entradas cercanas a hábitos reales de escucha." },
        { title: "Sistema de Acento Personalizado", description: "Las opciones de acento hacen que la interfaz se sienta más personal sin romper la previsibilidad de componentes." },
        { title: "Navegación Espacial", description: "La sidebar mantiene navegación, herramientas de playback y acciones de biblioteca accesibles sin romper el foco." },
        { title: "Núcleo de Reproducción", description: "La superficie del player reúne controles, portada y contexto de cola en una interfaz calma." },
        { title: "Flujo de Sleep Timer", description: "Timer y comportamiento en segundo plano se tratan como recursos de lifecycle, no como extras decorativos." },
        { title: "Matriz de Colecciones", description: "Pantallas de colección organizan metadatos locales, favoritos, recientes y playlists en flujos repetibles." },
        { title: "Dirección de Curaduría", description: "Historial de escucha y disponibilidad local pueden hacer que las colecciones sean más útiles con el tiempo." },
        { title: "Dirección Gapless", description: "Gapless se trata como capacidad dependiente de plataforma que exige validación en el pipeline real." },
        { title: "Superficie de Ecualizador", description: "Presets y controles de salida amplían el control del oyente manteniendo explícito el comportamiento DSP." },
        { title: "Estado Local", description: "La persistencia local mantiene cambios de biblioteca, playlists y preferencias cerca del dispositivo." },
        { title: "Experiencia de Audio Unificada", description: "La experiencia conecta posesión de biblioteca, confiabilidad de reproducción, widgets nativos y motion cuidadoso." },
        { title: "Velocidad de Reproducción", description: "Controles de velocidad apoyan escuchas flexibles dentro de la superficie normal del player." },
        { title: "Controles Contextuales", description: "Overlays mantienen controles avanzados disponibles sin saturar la capa activa de reproducción." },
      ],
    },
  },
} as const;