export const saasDataControlContent = {
  en: {
    hero: {
      badge: "Case Study // SaaS Data Control",
      title: "Task Manager",
      titleAccent: "Pro",
      description: "Task Manager Pro began as a CRUD study and became a practical exercise in SaaS architecture: secure sessions, scoped data access, reports and operational visibility.",
      stack: ["Java 17", "Spring Boot 3", "PostgreSQL"],
      imageAlt: "Task Manager Pro dashboard overview",
    },
    analytics: {
      badge: "Problem Context",
      title: "Work needs",
      titleAccent: "Visibility",
      description: "Task management looks simple until ownership, status, reporting and team context need to live in the same system. The dashboard represents that need for one operational view.",
      previewTitle: "analytics.dashboard.app",
      imageAlt: "Task Manager analytics dashboard",
      metrics: [
        { value: "Scope", label: "Task Ownership", trend: { value: "User", positive: true } },
        { value: "Flow", label: "Status Tracking", trend: { value: "Live", positive: true } },
        { value: "Risk", label: "Access Boundaries", trend: { value: "Scoped", positive: true } },
        { value: "Docs", label: "Reports", trend: { value: "Export", positive: true } },
      ],
    },
    architecture: {
      badge: "Engineering Decision",
      title: "Backend",
      titleAccent: "Boundaries",
      description: "The main decision is to keep business rules and ownership checks in backend layers instead of trusting only the interface. Controllers, services, repositories, DTOs, filters and report exporters each have a clear responsibility.",
      flowLabel: "REQUEST FLOW",
      flowSublabel: "From interface to scoped persistence",
      coreLabel: "CORE STACK",
      coreTitle: "Application Layers",
      flow: [
        { label: "Web Interface", desc: "Thymeleaf + Vite" },
        { label: "Spring Boot", desc: "Application Core" },
        { label: "Service Layer", desc: "Rules + Ownership" },
        { label: "JPA / Hibernate", desc: "Scoped Queries" },
        { label: "PostgreSQL", desc: "Persistent Storage" },
      ],
      features: [
        { label: "Spring Security", desc: "JWT + Refresh Tokens" },
        { label: "REST APIs", desc: "Explicit endpoints" },
        { label: "Service Layer", desc: "Business rules" },
        { label: "JPA", desc: "Repository access" },
        { label: "PostgreSQL", desc: "Relational model" },
      ],
    },
    challenges: {
      badge: "Problem",
      title: "Operational",
      titleAccent: "Friction",
      description: "The case starts from a common product problem: task systems become fragile when authentication, ownership, reporting and maintainability are added after the CRUD surface is already built.",
      status: "Design Risk",
      items: [
        { title: "Unclear Task Ownership", description: "Tasks need to be tied to the authenticated user or tenant so access rules do not depend on the UI alone.", tag: "OWNERSHIP" },
        { title: "Limited Operational Context", description: "Status, priorities and progress lose value when they are not presented in one coherent operational view.", tag: "VISIBILITY" },
        { title: "Scattered Reporting", description: "Manual report generation can make data slow to review, inconsistent or hard to reuse outside the app.", tag: "REPORTS" },
        { title: "Thin CRUD Boundaries", description: "A simple CRUD layer is not enough when sessions, authorization and exports become part of the product.", tag: "ARCHITECTURE" },
      ],
    },
    solution: {
      badge: "Solution",
      titleLine1: "A",
      titleAccent1: "Scoped",
      titleLine2: "Platform for",
      titleAccent2: "Operations",
      description: "The solution centralizes tasks, dashboards, reports and exports while keeping backend authorization tied to the authenticated user context.",
      previewTitle: "solution.dashboard.app",
      imageAlt: "Centralized operations solution dashboard",
      stats: [
        { label: "Access", value: "Scoped" },
        { label: "Reports", value: "PDF/XLSX" },
      ],
      items: [
        { label: "Task Management", description: "Tasks are handled as owned records, not just generic rows." },
        { label: "Operational Dashboard", description: "Status summaries organize work into a view teams can act on." },
        { label: "Exportable Reports", description: "PDF and XLSX exports keep reporting modular and replaceable." },
        { label: "Productivity Tracking", description: "Task state can be reviewed through structured operational signals." },
        { label: "Centralized Information", description: "Core work context stays in one application surface." },
      ],
    },
    features: {
      badge: "Capabilities",
      title: "Built around",
      titleAccent: "Safer",
      titleLine2: "Operations",
      description: "The feature set is presented as a study in how business software stays usable while authentication, reporting and data ownership become more serious.",
      items: [
        { tag: "SECURITY", title: "Secure Sessions", description: "Session handling is modeled with Spring Security, JWT access tokens and refresh token rotation." },
        { tag: "OWNERSHIP", title: "Scoped Data Access", description: "Repository access is designed around authenticated user context to mitigate horizontal data exposure." },
        { tag: "REPORTING", title: "PDF Reports", description: "PDF output supports analysis, review and operational handoff." },
        { tag: "EXPORT", title: "Excel Export", description: "XLSX exports keep structured task data available outside the application." },
        { tag: "UX", title: "Responsive Experience", description: "Adaptive layouts keep the task and dashboard flow usable across screen sizes." },
        { tag: "STORAGE", title: "PostgreSQL Persistence", description: "A relational model gives the project a durable foundation for users, tasks, tokens and reports." },
      ],
    },
    stack: {
      badge: "Development Stack",
      title: "Technology",
      titleAccent: "Stack",
      description: "The stack reflects a deliberate Java/Spring learning path: durable persistence, explicit service boundaries, modular frontend assets and replaceable reporting engines.",
      groups: [
        { id: "backend", title: "Backend", subtitle: "Core Runtime", status: "APPLICATION", technologies: [{ name: "Java 17", tag: "LTS" }, { name: "Spring Boot 3", tag: "Framework" }, { name: "Spring Security", tag: "Auth" }, { name: "REST APIs", tag: "HTTP" }] },
        { id: "data", title: "Data Layer", subtitle: "Persistence & ORM", status: "RELATIONAL", technologies: [{ name: "PostgreSQL", tag: "DB" }, { name: "JPA", tag: "Repository" }, { name: "Hibernate", tag: "ORM" }] },
        { id: "frontend", title: "Frontend", subtitle: "Presentation Layer", status: "MODULAR", technologies: [{ name: "Thymeleaf", tag: "Template" }, { name: "Vite", tag: "Bundler" }, { name: "SASS", tag: "Styles" }, { name: "Chart.js", tag: "Charts" }] },
        { id: "reporting", title: "Reporting", subtitle: "Document Generation", status: "EXPORT", technologies: [{ name: "Apache POI", tag: "XLSX" }, { name: "OpenPDF", tag: "PDF" }] },
      ],
    },
    final: {
      badge: "Result // Architecture Story",
      title: "From CRUD to",
      titleAccent: "Scoped",
      titleSuffix: "Operations",
      description: "Task Manager Pro presents a simple product surface backed by harder SaaS questions: who owns the data, how sessions stay controlled, and how reports remain modular as the system evolves.",
      metrics: [
        { value: "JWT", label: "Session Model" },
        { value: "PostgreSQL", label: "Relational Persistence" },
        { value: "Scoped", label: "User Data Access" },
      ],
    },
  },
  pt: {
    hero: {
      badge: "Estudo de Caso // SaaS Data Control",
      title: "Task Manager",
      titleAccent: "Pro",
      description: "O Task Manager Pro começou como um estudo de CRUD e evoluiu para um exercício prático de arquitetura SaaS: sessões seguras, acesso a dados com escopo, relatórios e visibilidade operacional.",
      stack: ["Java 17", "Spring Boot 3", "PostgreSQL"],
      imageAlt: "Visão geral do dashboard Task Manager Pro",
    },
    analytics: {
      badge: "Contexto do Problema",
      title: "Trabalho precisa de",
      titleAccent: "Visibilidade",
      description: "Gestão de tarefas parece simples até propriedade, status, relatórios e contexto de equipe precisarem viver no mesmo sistema. O dashboard representa essa necessidade de uma visão operacional única.",
      previewTitle: "analytics.dashboard.app",
      imageAlt: "Dashboard analítico do Task Manager",
      metrics: [
        { value: "Escopo", label: "Propriedade da Tarefa", trend: { value: "Usuário", positive: true } },
        { value: "Fluxo", label: "Acompanhamento", trend: { value: "Ativo", positive: true } },
        { value: "Risco", label: "Limites de Acesso", trend: { value: "Scoped", positive: true } },
        { value: "Docs", label: "Relatórios", trend: { value: "Export", positive: true } },
      ],
    },
    architecture: {
      badge: "Decisão de Engenharia",
      title: "Limites",
      titleAccent: "de Backend",
      description: "A decisão principal é manter regras de negócio e checagens de propriedade nas camadas de backend, em vez de confiar apenas na interface. Controllers, services, repositories, DTOs, filtros e exportadores de relatório têm responsabilidades claras.",
      flowLabel: "FLUXO DE REQUISIÇÃO",
      flowSublabel: "Da interface à persistência com escopo",
      coreLabel: "STACK PRINCIPAL",
      coreTitle: "Camadas da Aplicação",
      flow: [
        { label: "Interface Web", desc: "Thymeleaf + Vite" },
        { label: "Spring Boot", desc: "Core da Aplicação" },
        { label: "Camada de Serviços", desc: "Regras + Propriedade" },
        { label: "JPA / Hibernate", desc: "Consultas com Escopo" },
        { label: "PostgreSQL", desc: "Armazenamento Persistente" },
      ],
      features: [
        { label: "Spring Security", desc: "JWT + Refresh Tokens" },
        { label: "REST APIs", desc: "Endpoints explícitos" },
        { label: "Service Layer", desc: "Regras de negócio" },
        { label: "JPA", desc: "Acesso por repository" },
        { label: "PostgreSQL", desc: "Modelo relacional" },
      ],
    },
    challenges: {
      badge: "Problema",
      title: "Fricção",
      titleAccent: "Operacional",
      description: "O case parte de um problema comum de produto: sistemas de tarefas ficam frágeis quando autenticação, propriedade, relatórios e manutenção entram depois da superfície CRUD já existir.",
      status: "Risco de Design",
      items: [
        { title: "Propriedade de Tarefa Pouco Clara", description: "Tarefas precisam estar ligadas ao usuário ou tenant autenticado para que as regras de acesso não dependam apenas da UI.", tag: "OWNERSHIP" },
        { title: "Contexto Operacional Limitado", description: "Status, prioridades e progresso perdem valor quando não aparecem em uma visão operacional coerente.", tag: "VISIBILIDADE" },
        { title: "Relatórios Dispersos", description: "Relatórios manuais podem tornar dados lentos de revisar, inconsistentes ou difíceis de reutilizar fora do app.", tag: "RELATÓRIOS" },
        { title: "Limites CRUD Rasos", description: "Uma camada CRUD simples não basta quando sessões, autorização e exportações passam a fazer parte do produto.", tag: "ARQUITETURA" },
      ],
    },
    solution: {
      badge: "Solução",
      titleLine1: "Uma",
      titleAccent1: "Plataforma",
      titleLine2: "Com Escopo para",
      titleAccent2: "Operações",
      description: "A solução centraliza tarefas, dashboards, relatórios e exportações mantendo a autorização do backend ligada ao contexto do usuário autenticado.",
      previewTitle: "solution.dashboard.app",
      imageAlt: "Dashboard da solução operacional centralizada",
      stats: [
        { label: "Acesso", value: "Scoped" },
        { label: "Relatórios", value: "PDF/XLSX" },
      ],
      items: [
        { label: "Gestão de Tarefas", description: "Tarefas são tratadas como registros com dono, não apenas linhas genéricas." },
        { label: "Dashboard Operacional", description: "Resumo de status organiza o trabalho em uma visão acionável." },
        { label: "Relatórios Exportáveis", description: "PDF e XLSX mantêm a geração de relatórios modular e substituível." },
        { label: "Rastreamento de Produtividade", description: "O estado das tarefas pode ser revisado por sinais operacionais estruturados." },
        { label: "Informação Centralizada", description: "O contexto central do trabalho permanece em uma única superfície de aplicação." },
      ],
    },
    features: {
      badge: "Capacidades",
      title: "Criado para",
      titleAccent: "Operações",
      titleLine2: "Mais Seguras",
      description: "O conjunto de recursos é apresentado como um estudo de como software de negócio continua utilizável enquanto autenticação, relatórios e propriedade de dados ficam mais sérios.",
      items: [
        { tag: "SEGURANÇA", title: "Sessões Seguras", description: "O tratamento de sessão é modelado com Spring Security, access tokens JWT e rotação de refresh tokens." },
        { tag: "OWNERSHIP", title: "Acesso a Dados com Escopo", description: "O acesso por repository é projetado em torno do usuário autenticado para mitigar exposição horizontal de dados." },
        { tag: "RELATÓRIOS", title: "Relatórios PDF", description: "A saída em PDF apoia análise, revisão e passagem operacional." },
        { tag: "EXPORT", title: "Exportação Excel", description: "Exportações XLSX mantêm dados estruturados de tarefas disponíveis fora da aplicação." },
        { tag: "UX", title: "Experiência Responsiva", description: "Layouts adaptativos mantêm o fluxo de tarefas e dashboard utilizável em diferentes tamanhos de tela." },
        { tag: "DADOS", title: "Persistência PostgreSQL", description: "Um modelo relacional dá base durável para usuários, tarefas, tokens e relatórios." },
      ],
    },
    stack: {
      badge: "Stack de Desenvolvimento",
      title: "Stack",
      titleAccent: "Tecnológica",
      description: "A stack reflete um caminho deliberado em Java/Spring: persistência durável, fronteiras explícitas de serviço, assets frontend modulares e mecanismos de relatório substituíveis.",
      groups: [
        { id: "backend", title: "Backend", subtitle: "Runtime Principal", status: "APLICAÇÃO", technologies: [{ name: "Java 17", tag: "LTS" }, { name: "Spring Boot 3", tag: "Framework" }, { name: "Spring Security", tag: "Auth" }, { name: "REST APIs", tag: "HTTP" }] },
        { id: "data", title: "Camada de Dados", subtitle: "Persistência & ORM", status: "RELACIONAL", technologies: [{ name: "PostgreSQL", tag: "DB" }, { name: "JPA", tag: "Repository" }, { name: "Hibernate", tag: "ORM" }] },
        { id: "frontend", title: "Frontend", subtitle: "Camada de Apresentação", status: "MODULAR", technologies: [{ name: "Thymeleaf", tag: "Template" }, { name: "Vite", tag: "Bundler" }, { name: "SASS", tag: "Styles" }, { name: "Chart.js", tag: "Charts" }] },
        { id: "reporting", title: "Relatórios", subtitle: "Geração de Documentos", status: "EXPORT", technologies: [{ name: "Apache POI", tag: "XLSX" }, { name: "OpenPDF", tag: "PDF" }] },
      ],
    },
    final: {
      badge: "Resultado // História de Arquitetura",
      title: "De CRUD para",
      titleAccent: "Operações",
      titleSuffix: "Com Escopo",
      description: "O Task Manager Pro apresenta uma superfície simples de produto apoiada por perguntas mais difíceis de SaaS: quem é dono do dado, como sessões continuam controladas e como relatórios permanecem modulares conforme o sistema evolui.",
      metrics: [
        { value: "JWT", label: "Modelo de Sessão" },
        { value: "PostgreSQL", label: "Persistência Relacional" },
        { value: "Scoped", label: "Acesso por Usuário" },
      ],
    },
  },
  es: {
    hero: {
      badge: "Caso de Estudio // SaaS Data Control",
      title: "Task Manager",
      titleAccent: "Pro",
      description: "Task Manager Pro comenzó como un estudio de CRUD y evolucionó hacia un ejercicio práctico de arquitectura SaaS: sesiones seguras, acceso a datos con alcance, reportes y visibilidad operacional.",
      stack: ["Java 17", "Spring Boot 3", "PostgreSQL"],
      imageAlt: "Vista general del dashboard Task Manager Pro",
    },
    analytics: {
      badge: "Contexto del Problema",
      title: "El trabajo necesita",
      titleAccent: "Visibilidad",
      description: "La gestión de tareas parece simple hasta que propiedad, estado, reportes y contexto de equipo necesitan vivir en el mismo sistema. El dashboard representa esa necesidad de una vista operacional única.",
      previewTitle: "analytics.dashboard.app",
      imageAlt: "Dashboard analítico de Task Manager",
      metrics: [
        { value: "Alcance", label: "Propiedad de Tarea", trend: { value: "Usuario", positive: true } },
        { value: "Flujo", label: "Seguimiento", trend: { value: "Activo", positive: true } },
        { value: "Riesgo", label: "Límites de Acceso", trend: { value: "Scoped", positive: true } },
        { value: "Docs", label: "Reportes", trend: { value: "Export", positive: true } },
      ],
    },
    architecture: {
      badge: "Decisión de Ingeniería",
      title: "Límites",
      titleAccent: "de Backend",
      description: "La decisión principal es mantener reglas de negocio y chequeos de propiedad en las capas de backend, en vez de confiar solo en la interfaz. Controllers, services, repositories, DTOs, filtros y exportadores de reportes tienen responsabilidades claras.",
      flowLabel: "FLUJO DE SOLICITUD",
      flowSublabel: "De la interfaz a la persistencia con alcance",
      coreLabel: "STACK PRINCIPAL",
      coreTitle: "Capas de la Aplicación",
      flow: [
        { label: "Interfaz Web", desc: "Thymeleaf + Vite" },
        { label: "Spring Boot", desc: "Core de Aplicación" },
        { label: "Capa de Servicios", desc: "Reglas + Propiedad" },
        { label: "JPA / Hibernate", desc: "Consultas con Alcance" },
        { label: "PostgreSQL", desc: "Almacenamiento Persistente" },
      ],
      features: [
        { label: "Spring Security", desc: "JWT + Refresh Tokens" },
        { label: "REST APIs", desc: "Endpoints explícitos" },
        { label: "Service Layer", desc: "Reglas de negocio" },
        { label: "JPA", desc: "Acceso por repository" },
        { label: "PostgreSQL", desc: "Modelo relacional" },
      ],
    },
    challenges: {
      badge: "Problema",
      title: "Fricción",
      titleAccent: "Operacional",
      description: "El caso parte de un problema común de producto: los sistemas de tareas se vuelven frágiles cuando autenticación, propiedad, reportes y mantenimiento entran después de que la superficie CRUD ya existe.",
      status: "Riesgo de Diseño",
      items: [
        { title: "Propiedad de Tarea Poco Clara", description: "Las tareas necesitan estar ligadas al usuario o tenant autenticado para que las reglas de acceso no dependan solo de la UI.", tag: "OWNERSHIP" },
        { title: "Contexto Operacional Limitado", description: "Estado, prioridades y progreso pierden valor cuando no aparecen en una vista operacional coherente.", tag: "VISIBILIDAD" },
        { title: "Reportes Dispersos", description: "Reportes manuales pueden volver los datos lentos de revisar, inconsistentes o difíciles de reutilizar fuera de la app.", tag: "REPORTES" },
        { title: "Límites CRUD Superficiales", description: "Una capa CRUD simple no basta cuando sesiones, autorización y exportaciones pasan a formar parte del producto.", tag: "ARQUITECTURA" },
      ],
    },
    solution: {
      badge: "Solución",
      titleLine1: "Una",
      titleAccent1: "Plataforma",
      titleLine2: "Con Alcance para",
      titleAccent2: "Operaciones",
      description: "La solución centraliza tareas, dashboards, reportes y exportaciones manteniendo la autorización del backend ligada al contexto del usuario autenticado.",
      previewTitle: "solution.dashboard.app",
      imageAlt: "Dashboard de la solución operacional centralizada",
      stats: [
        { label: "Acceso", value: "Scoped" },
        { label: "Reportes", value: "PDF/XLSX" },
      ],
      items: [
        { label: "Gestión de Tareas", description: "Las tareas se tratan como registros con dueño, no solo filas genéricas." },
        { label: "Dashboard Operacional", description: "Resumen de estado organiza el trabajo en una vista accionable." },
        { label: "Reportes Exportables", description: "PDF y XLSX mantienen la generación de reportes modular y reemplazable." },
        { label: "Seguimiento de Productividad", description: "El estado de tareas puede revisarse mediante señales operacionales estructuradas." },
        { label: "Información Centralizada", description: "El contexto central del trabajo permanece en una única superficie de aplicación." },
      ],
    },
    features: {
      badge: "Capacidades",
      title: "Creado para",
      titleAccent: "Operaciones",
      titleLine2: "Más Seguras",
      description: "El conjunto de recursos se presenta como un estudio de cómo el software de negocio sigue siendo usable mientras autenticación, reportes y propiedad de datos se vuelven más serios.",
      items: [
        { tag: "SEGURIDAD", title: "Sesiones Seguras", description: "El manejo de sesión se modela con Spring Security, access tokens JWT y rotación de refresh tokens." },
        { tag: "OWNERSHIP", title: "Acceso a Datos con Alcance", description: "El acceso por repository se diseña alrededor del usuario autenticado para mitigar exposición horizontal de datos." },
        { tag: "REPORTES", title: "Reportes PDF", description: "La salida en PDF apoya análisis, revisión y traspaso operacional." },
        { tag: "EXPORT", title: "Exportación Excel", description: "Exportaciones XLSX mantienen datos estructurados de tareas disponibles fuera de la aplicación." },
        { tag: "UX", title: "Experiencia Responsiva", description: "Layouts adaptativos mantienen el flujo de tareas y dashboard usable en distintos tamaños de pantalla." },
        { tag: "DATOS", title: "Persistencia PostgreSQL", description: "Un modelo relacional da base durable para usuarios, tareas, tokens y reportes." },
      ],
    },
    stack: {
      badge: "Stack de Desarrollo",
      title: "Stack",
      titleAccent: "Tecnológico",
      description: "La stack refleja un camino deliberado en Java/Spring: persistencia durable, fronteras explícitas de servicio, assets frontend modulares y mecanismos de reporte reemplazables.",
      groups: [
        { id: "backend", title: "Backend", subtitle: "Runtime Principal", status: "APLICACIÓN", technologies: [{ name: "Java 17", tag: "LTS" }, { name: "Spring Boot 3", tag: "Framework" }, { name: "Spring Security", tag: "Auth" }, { name: "REST APIs", tag: "HTTP" }] },
        { id: "data", title: "Capa de Datos", subtitle: "Persistencia & ORM", status: "RELACIONAL", technologies: [{ name: "PostgreSQL", tag: "DB" }, { name: "JPA", tag: "Repository" }, { name: "Hibernate", tag: "ORM" }] },
        { id: "frontend", title: "Frontend", subtitle: "Capa de Presentación", status: "MODULAR", technologies: [{ name: "Thymeleaf", tag: "Template" }, { name: "Vite", tag: "Bundler" }, { name: "SASS", tag: "Styles" }, { name: "Chart.js", tag: "Charts" }] },
        { id: "reporting", title: "Reportes", subtitle: "Generación de Documentos", status: "EXPORT", technologies: [{ name: "Apache POI", tag: "XLSX" }, { name: "OpenPDF", tag: "PDF" }] },
      ],
    },
    final: {
      badge: "Resultado // Historia de Arquitectura",
      title: "De CRUD a",
      titleAccent: "Operaciones",
      titleSuffix: "Con Alcance",
      description: "Task Manager Pro presenta una superficie simple de producto apoyada por preguntas más difíciles de SaaS: quién es dueño del dato, cómo las sesiones permanecen controladas y cómo los reportes siguen modulares mientras el sistema evoluciona.",
      metrics: [
        { value: "JWT", label: "Modelo de Sesión" },
        { value: "PostgreSQL", label: "Persistencia Relacional" },
        { value: "Scoped", label: "Acceso por Usuario" },
      ],
    },
  },
} as const;