export const saasDataControlContent = {
  en: {
    hero: {
      badge: "Enterprise Productivity Platform",
      title: "Task Manager",
      titleAccent: "Pro",
      description: "Corporate platform developed for task management, productivity and operational monitoring at enterprise scale.",
      stack: ["Java 17", "Spring Boot 3", "PostgreSQL"],
      imageAlt: "Task Manager Pro dashboard overview",
    },
    analytics: {
      badge: "Live Metrics",
      title: "Indicators in",
      titleAccent: "Real Time",
      description: "Track operational metrics, productivity and task progress in a single high-performance corporate environment.",
      previewTitle: "analytics.dashboard.app",
      imageAlt: "Task Manager analytics dashboard",
      metrics: [
        { value: "127", label: "Total Tasks", trend: { value: "12%", positive: true } },
        { value: "94", label: "Completed", trend: { value: "8%", positive: true } },
        { value: "23", label: "In Progress", trend: { value: "3%", positive: false } },
        { value: "10", label: "Overdue", trend: { value: "5%", positive: false } },
      ],
    },
    architecture: {
      badge: "System Architecture",
      title: "Architecture",
      titleAccent: "Enterprise",
      description: "A layered structure designed for scalability, maintainability and continuous evolution in high-availability environments.",
      flowLabel: "DATA FLOW",
      flowSublabel: "Request to response pipeline",
      coreLabel: "CORE STACK",
      coreTitle: "Enterprise Technologies",
      flow: [
        { label: "Web Interface", desc: "React + TypeScript" },
        { label: "Spring Boot", desc: "REST API Gateway" },
        { label: "Service Layer", desc: "Business Logic" },
        { label: "JPA / Hibernate", desc: "ORM Layer" },
        { label: "PostgreSQL", desc: "Persistent Storage" },
      ],
      features: [
        { label: "Spring Security", desc: "JWT + OAuth2" },
        { label: "REST APIs", desc: "RESTful endpoints" },
        { label: "MVC Pattern", desc: "Clean architecture" },
        { label: "JPA", desc: "Data persistence" },
        { label: "PostgreSQL", desc: "ACID compliance" },
      ],
    },
    challenges: {
      badge: "Pain Points",
      title: "Operational",
      titleAccent: "Challenges",
      description: "Many teams struggle with fragmented processes, limited visibility and manual task tracking that slow down business operations.",
      status: "Critical Issue",
      items: [
        { title: "Decentralized Task Control", description: "Tasks spread across multiple tools and disconnected workflows creating operational noise.", tag: "WORKFLOW" },
        { title: "Limited Operational Visibility", description: "Difficulty tracking progress, bottlenecks and real team productivity across departments.", tag: "VISIBILITY" },
        { title: "Scattered Reporting", description: "Reports generated manually from multiple sources, resulting in delayed and inconsistent data.", tag: "DATA" },
        { title: "Manual Tracking Processes", description: "Operational activities monitored through repetitive manual tasks consuming valuable time.", tag: "EFFICIENCY" },
      ],
    },
    solution: {
      badge: "The Solution",
      titleLine1: "A",
      titleAccent1: "Centralized",
      titleLine2: "Platform for",
      titleAccent2: "Operations",
      description: "A single enterprise platform designed to organize workflows, monitor progress and restore full operational visibility across your organization.",
      previewTitle: "solution.dashboard.app",
      imageAlt: "Centralized operations solution dashboard",
      stats: [
        { label: "Operational Efficiency", value: "+87%" },
        { label: "Tasks Completed", value: "1,247" },
      ],
      items: [
        { label: "Task Management", description: "Centralized control over all operational tasks" },
        { label: "Real-Time Dashboard", description: "Live monitoring of KPIs and team performance" },
        { label: "Exportable Reports", description: "One-click generation of professional reports" },
        { label: "Productivity Tracking", description: "Data-driven insights on operational efficiency" },
        { label: "Centralized Information", description: "Single source of truth for the entire team" },
      ],
    },
    features: {
      badge: "Enterprise Capabilities",
      title: "Built for",
      titleAccent: "Corporate",
      titleLine2: "Operations",
      description: "A comprehensive suite of enterprise-grade features engineered to support operational efficiency, security compliance and long-term business growth.",
      items: [
        { tag: "SECURITY", title: "Secure Authentication", description: "Role-based access control implemented with Spring Security and JWT token management." },
        { tag: "ANALYTICS", title: "Analytics Dashboard", description: "Real-time metrics and operational visibility with customizable KPI monitoring." },
        { tag: "REPORTING", title: "PDF Reports", description: "Generate professional reports for analysis, auditing and executive presentations." },
        { tag: "EXPORT", title: "Excel Export", description: "Export structured data in XLSX format for external processing and integration." },
        { tag: "UX", title: "Responsive Experience", description: "Consistent usability across desktop, tablet and mobile devices with adaptive layouts." },
        { tag: "STORAGE", title: "PostgreSQL Persistence", description: "Reliable data storage with scalable relational modeling and ACID compliance." },
      ],
    },
    stack: {
      badge: "Development Stack",
      title: "Technology",
      titleAccent: "Stack",
      description: "Modern enterprise-grade technologies carefully selected to provide reliability, maintainability and long-term scalability.",
      groups: [
        { id: "backend", title: "Backend", subtitle: "Core Runtime", status: "PRODUCTION READY", technologies: [{ name: "Java 17", tag: "LTS" }, { name: "Spring Boot 3", tag: "Latest" }, { name: "Spring Security", tag: "Stable" }, { name: "REST APIs", tag: "Standard" }] },
        { id: "data", title: "Data Layer", subtitle: "Persistence & ORM", status: "ENTERPRISE GRADE", technologies: [{ name: "PostgreSQL", tag: "ACID" }, { name: "JPA", tag: "Standard" }, { name: "Hibernate", tag: "Stable" }] },
        { id: "frontend", title: "Frontend", subtitle: "Presentation Layer", status: "RESPONSIVE", technologies: [{ name: "Thymeleaf", tag: "Template" }, { name: "Bootstrap", tag: "Framework" }, { name: "Chart.js", tag: "Visualization" }] },
        { id: "reporting", title: "Reporting", subtitle: "Document Generation", status: "AUDIT READY", technologies: [{ name: "Apache POI", tag: "XLSX" }, { name: "iText", tag: "PDF" }] },
      ],
    },
    final: {
      badge: "Production Ready",
      title: "Ready to Scale in the",
      titleAccent: "Enterprise",
      titleSuffix: "Landscape",
      description: "saas_data_control consolidates clean architecture, robust Java performance and a polished user experience under high corporate demands.",
      metrics: [
        { value: "< 45ms", label: "Response Time (API)" },
        { value: "100% ACID", label: "Relational Persistence" },
        { value: "Zero Leak", label: "Memory Management" },
      ],
    },
  },
  pt: {
    hero: {
      badge: "Plataforma Corporativa de Produtividade",
      title: "Task Manager",
      titleAccent: "Pro",
      description: "Plataforma corporativa desenvolvida para gestão de tarefas, produtividade e monitoramento operacional em escala empresarial.",
      stack: ["Java 17", "Spring Boot 3", "PostgreSQL"],
      imageAlt: "Visão geral do dashboard Task Manager Pro",
    },
    analytics: {
      badge: "Métricas ao Vivo",
      title: "Indicadores em",
      titleAccent: "Tempo Real",
      description: "Acompanhe métricas operacionais, produtividade e progresso das tarefas em um único ambiente corporativo de alta performance.",
      previewTitle: "analytics.dashboard.app",
      imageAlt: "Dashboard analítico do Task Manager",
      metrics: [
        { value: "127", label: "Total de Tarefas", trend: { value: "12%", positive: true } },
        { value: "94", label: "Concluídas", trend: { value: "8%", positive: true } },
        { value: "23", label: "Em Andamento", trend: { value: "3%", positive: false } },
        { value: "10", label: "Atrasadas", trend: { value: "5%", positive: false } },
      ],
    },
    architecture: {
      badge: "Arquitetura do Sistema",
      title: "Arquitetura",
      titleAccent: "Enterprise",
      description: "Uma estrutura em camadas criada para escalabilidade, manutenção e evolução contínua em ambientes de alta disponibilidade.",
      flowLabel: "FLUXO DE DADOS",
      flowSublabel: "Pipeline de requisição para resposta",
      coreLabel: "STACK PRINCIPAL",
      coreTitle: "Tecnologias Enterprise",
      flow: [
        { label: "Interface Web", desc: "React + TypeScript" },
        { label: "Spring Boot", desc: "Gateway REST API" },
        { label: "Camada de Serviços", desc: "Lógica de Negócio" },
        { label: "JPA / Hibernate", desc: "Camada ORM" },
        { label: "PostgreSQL", desc: "Armazenamento Persistente" },
      ],
      features: [
        { label: "Spring Security", desc: "JWT + OAuth2" },
        { label: "REST APIs", desc: "Endpoints RESTful" },
        { label: "Padrão MVC", desc: "Arquitetura limpa" },
        { label: "JPA", desc: "Persistência de dados" },
        { label: "PostgreSQL", desc: "Conformidade ACID" },
      ],
    },
    challenges: {
      badge: "Pontos de Dor",
      title: "Desafios",
      titleAccent: "Operacionais",
      description: "Muitas equipes enfrentam processos fragmentados, pouca visibilidade e acompanhamento manual de tarefas que desaceleram a operação.",
      status: "Questão Crítica",
      items: [
        { title: "Controle de Tarefas Descentralizado", description: "Tarefas espalhadas por várias ferramentas e fluxos desconectados gerando ruído operacional.", tag: "WORKFLOW" },
        { title: "Visibilidade Operacional Limitada", description: "Dificuldade para acompanhar progresso, gargalos e produtividade real entre departamentos.", tag: "VISIBILIDADE" },
        { title: "Relatórios Dispersos", description: "Relatórios montados manualmente a partir de várias fontes, com dados atrasados e inconsistentes.", tag: "DADOS" },
        { title: "Processos de Controle Manuais", description: "Atividades operacionais monitoradas por tarefas repetitivas que consomem tempo valioso.", tag: "EFICIÊNCIA" },
      ],
    },
    solution: {
      badge: "A Solução",
      titleLine1: "Uma",
      titleAccent1: "Plataforma",
      titleLine2: "Centralizada para",
      titleAccent2: "Operações",
      description: "Uma plataforma corporativa única para organizar fluxos, monitorar progresso e restaurar visibilidade operacional completa.",
      previewTitle: "solution.dashboard.app",
      imageAlt: "Dashboard da solução operacional centralizada",
      stats: [
        { label: "Eficiência Operacional", value: "+87%" },
        { label: "Tarefas Concluídas", value: "1.247" },
      ],
      items: [
        { label: "Gestão de Tarefas", description: "Controle centralizado de todas as tarefas operacionais" },
        { label: "Dashboard em Tempo Real", description: "Monitoramento ao vivo de KPIs e performance da equipe" },
        { label: "Relatórios Exportáveis", description: "Geração de relatórios profissionais em um clique" },
        { label: "Rastreamento de Produtividade", description: "Insights orientados por dados sobre eficiência operacional" },
        { label: "Informação Centralizada", description: "Fonte única de verdade para toda a equipe" },
      ],
    },
    features: {
      badge: "Capacidades Enterprise",
      title: "Criado para",
      titleAccent: "Operações",
      titleLine2: "Corporativas",
      description: "Um conjunto completo de recursos enterprise criado para apoiar eficiência operacional, segurança e crescimento de longo prazo.",
      items: [
        { tag: "SEGURANÇA", title: "Autenticação Segura", description: "Controle de acesso por perfil implementado com Spring Security e tokens JWT." },
        { tag: "ANALYTICS", title: "Dashboard Analítico", description: "Métricas em tempo real e visibilidade operacional com monitoramento personalizável de KPIs." },
        { tag: "RELATÓRIOS", title: "Relatórios PDF", description: "Geração de relatórios profissionais para análise, auditoria e apresentações executivas." },
        { tag: "EXPORTAÇÃO", title: "Exportação Excel", description: "Exportação de dados estruturados em XLSX para processamento e integração externos." },
        { tag: "UX", title: "Experiência Responsiva", description: "Usabilidade consistente em desktop, tablet e mobile com layouts adaptativos." },
        { tag: "DADOS", title: "Persistência PostgreSQL", description: "Armazenamento confiável com modelagem relacional escalável e conformidade ACID." },
      ],
    },
    stack: {
      badge: "Stack de Desenvolvimento",
      title: "Stack",
      titleAccent: "Tecnológica",
      description: "Tecnologias modernas de nível enterprise selecionadas para confiabilidade, manutenção e escalabilidade de longo prazo.",
      groups: [
        { id: "backend", title: "Backend", subtitle: "Runtime Principal", status: "PRONTO PARA PRODUÇÃO", technologies: [{ name: "Java 17", tag: "LTS" }, { name: "Spring Boot 3", tag: "Atual" }, { name: "Spring Security", tag: "Estável" }, { name: "REST APIs", tag: "Padrão" }] },
        { id: "data", title: "Camada de Dados", subtitle: "Persistência & ORM", status: "NÍVEL ENTERPRISE", technologies: [{ name: "PostgreSQL", tag: "ACID" }, { name: "JPA", tag: "Padrão" }, { name: "Hibernate", tag: "Estável" }] },
        { id: "frontend", title: "Frontend", subtitle: "Camada de Apresentação", status: "RESPONSIVO", technologies: [{ name: "Thymeleaf", tag: "Template" }, { name: "Bootstrap", tag: "Framework" }, { name: "Chart.js", tag: "Visualização" }] },
        { id: "reporting", title: "Relatórios", subtitle: "Geração de Documentos", status: "PRONTO PARA AUDITORIA", technologies: [{ name: "Apache POI", tag: "XLSX" }, { name: "iText", tag: "PDF" }] },
      ],
    },
    final: {
      badge: "Pronto para Produção",
      title: "Pronto para Escalar no",
      titleAccent: "Ambiente",
      titleSuffix: "Enterprise",
      description: "saas_data_control consolida arquitetura limpa, performance robusta em Java e uma experiência polida para demandas corporativas altas.",
      metrics: [
        { value: "< 45ms", label: "Tempo de Resposta (API)" },
        { value: "100% ACID", label: "Persistência Relacional" },
        { value: "Zero Leak", label: "Gestão de Memória" },
      ],
    },
  },
  es: {
    hero: {
      badge: "Plataforma Corporativa de Productividad",
      title: "Task Manager",
      titleAccent: "Pro",
      description: "Plataforma corporativa desarrollada para gestión de tareas, productividad y monitoreo operacional a escala empresarial.",
      stack: ["Java 17", "Spring Boot 3", "PostgreSQL"],
      imageAlt: "Vista general del dashboard Task Manager Pro",
    },
    analytics: {
      badge: "Métricas en Vivo",
      title: "Indicadores en",
      titleAccent: "Tiempo Real",
      description: "Monitorea métricas operacionales, productividad y progreso de tareas en un único entorno corporativo de alto rendimiento.",
      previewTitle: "analytics.dashboard.app",
      imageAlt: "Dashboard analítico de Task Manager",
      metrics: [
        { value: "127", label: "Total de Tareas", trend: { value: "12%", positive: true } },
        { value: "94", label: "Completadas", trend: { value: "8%", positive: true } },
        { value: "23", label: "En Progreso", trend: { value: "3%", positive: false } },
        { value: "10", label: "Atrasadas", trend: { value: "5%", positive: false } },
      ],
    },
    architecture: {
      badge: "Arquitectura del Sistema",
      title: "Arquitectura",
      titleAccent: "Enterprise",
      description: "Una estructura por capas diseñada para escalabilidad, mantenibilidad y evolución continua en entornos de alta disponibilidad.",
      flowLabel: "FLUJO DE DATOS",
      flowSublabel: "Pipeline de solicitud a respuesta",
      coreLabel: "STACK PRINCIPAL",
      coreTitle: "Tecnologías Enterprise",
      flow: [
        { label: "Interfaz Web", desc: "React + TypeScript" },
        { label: "Spring Boot", desc: "Gateway REST API" },
        { label: "Capa de Servicios", desc: "Lógica de Negocio" },
        { label: "JPA / Hibernate", desc: "Capa ORM" },
        { label: "PostgreSQL", desc: "Almacenamiento Persistente" },
      ],
      features: [
        { label: "Spring Security", desc: "JWT + OAuth2" },
        { label: "REST APIs", desc: "Endpoints RESTful" },
        { label: "Patrón MVC", desc: "Arquitectura limpia" },
        { label: "JPA", desc: "Persistencia de datos" },
        { label: "PostgreSQL", desc: "Cumplimiento ACID" },
      ],
    },
    challenges: {
      badge: "Puntos de Dolor",
      title: "Desafíos",
      titleAccent: "Operacionales",
      description: "Muchos equipos enfrentan procesos fragmentados, baja visibilidad y seguimiento manual de tareas que ralentizan la operación.",
      status: "Problema Crítico",
      items: [
        { title: "Control de Tareas Descentralizado", description: "Tareas dispersas en múltiples herramientas y flujos desconectados que generan ruido operacional.", tag: "WORKFLOW" },
        { title: "Visibilidad Operacional Limitada", description: "Dificultad para seguir progreso, cuellos de botella y productividad real entre departamentos.", tag: "VISIBILIDAD" },
        { title: "Reportes Dispersos", description: "Reportes generados manualmente desde varias fuentes, con datos tardíos e inconsistentes.", tag: "DATOS" },
        { title: "Procesos de Seguimiento Manuales", description: "Actividades operacionales monitoreadas con tareas repetitivas que consumen tiempo valioso.", tag: "EFICIENCIA" },
      ],
    },
    solution: {
      badge: "La Solución",
      titleLine1: "Una",
      titleAccent1: "Plataforma",
      titleLine2: "Centralizada para",
      titleAccent2: "Operaciones",
      description: "Una plataforma corporativa única para organizar flujos, monitorear progreso y recuperar visibilidad operacional completa.",
      previewTitle: "solution.dashboard.app",
      imageAlt: "Dashboard de la solución operacional centralizada",
      stats: [
        { label: "Eficiencia Operacional", value: "+87%" },
        { label: "Tareas Completadas", value: "1.247" },
      ],
      items: [
        { label: "Gestión de Tareas", description: "Control centralizado de todas las tareas operacionales" },
        { label: "Dashboard en Tiempo Real", description: "Monitoreo en vivo de KPIs y rendimiento del equipo" },
        { label: "Reportes Exportables", description: "Generación de reportes profesionales en un clic" },
        { label: "Seguimiento de Productividad", description: "Insights basados en datos sobre eficiencia operacional" },
        { label: "Información Centralizada", description: "Fuente única de verdad para todo el equipo" },
      ],
    },
    features: {
      badge: "Capacidades Enterprise",
      title: "Creado para",
      titleAccent: "Operaciones",
      titleLine2: "Corporativas",
      description: "Un conjunto completo de recursos enterprise diseñado para apoyar eficiencia operacional, seguridad y crecimiento de largo plazo.",
      items: [
        { tag: "SEGURIDAD", title: "Autenticación Segura", description: "Control de acceso por roles implementado con Spring Security y tokens JWT." },
        { tag: "ANALYTICS", title: "Dashboard Analítico", description: "Métricas en tiempo real y visibilidad operacional con monitoreo personalizable de KPIs." },
        { tag: "REPORTES", title: "Reportes PDF", description: "Generación de reportes profesionales para análisis, auditoría y presentaciones ejecutivas." },
        { tag: "EXPORTACIÓN", title: "Exportación Excel", description: "Exportación de datos estructurados en XLSX para procesamiento e integración externos." },
        { tag: "UX", title: "Experiencia Responsiva", description: "Usabilidad consistente en desktop, tablet y móvil con layouts adaptativos." },
        { tag: "DATOS", title: "Persistencia PostgreSQL", description: "Almacenamiento confiable con modelado relacional escalable y cumplimiento ACID." },
      ],
    },
    stack: {
      badge: "Stack de Desarrollo",
      title: "Stack",
      titleAccent: "Tecnológico",
      description: "Tecnologías modernas de nivel enterprise seleccionadas para confiabilidad, mantenimiento y escalabilidad de largo plazo.",
      groups: [
        { id: "backend", title: "Backend", subtitle: "Runtime Principal", status: "LISTO PARA PRODUCCIÓN", technologies: [{ name: "Java 17", tag: "LTS" }, { name: "Spring Boot 3", tag: "Actual" }, { name: "Spring Security", tag: "Estable" }, { name: "REST APIs", tag: "Estándar" }] },
        { id: "data", title: "Capa de Datos", subtitle: "Persistencia & ORM", status: "NIVEL ENTERPRISE", technologies: [{ name: "PostgreSQL", tag: "ACID" }, { name: "JPA", tag: "Estándar" }, { name: "Hibernate", tag: "Estable" }] },
        { id: "frontend", title: "Frontend", subtitle: "Capa de Presentación", status: "RESPONSIVO", technologies: [{ name: "Thymeleaf", tag: "Template" }, { name: "Bootstrap", tag: "Framework" }, { name: "Chart.js", tag: "Visualización" }] },
        { id: "reporting", title: "Reportes", subtitle: "Generación de Documentos", status: "LISTO PARA AUDITORÍA", technologies: [{ name: "Apache POI", tag: "XLSX" }, { name: "iText", tag: "PDF" }] },
      ],
    },
    final: {
      badge: "Listo para Producción",
      title: "Listo para Escalar en el",
      titleAccent: "Entorno",
      titleSuffix: "Enterprise",
      description: "saas_data_control consolida arquitectura limpia, rendimiento robusto en Java y una experiencia pulida para altas demandas corporativas.",
      metrics: [
        { value: "< 45ms", label: "Tiempo de Respuesta (API)" },
        { value: "100% ACID", label: "Persistencia Relacional" },
        { value: "Zero Leak", label: "Gestión de Memoria" },
      ],
    },
  },
} as const;
