export const ecosystemContent = {
  en: {
    hero: {
      label: "ACT IV",
      titleLine1: "FOUR",
      titleAccent1: "CASES.",
      titleLine2: "ONE",
      titleAccent2: "SYSTEM.",
      descriptionStart: "A case-study ecosystem connecting",
      domains: ["experience", "learning", "productivity", "evidence"],
    },
    connected: {
      label: "RESULT",
      titleLine1: "Connected",
      titleAccent1: "Cases.",
      titleLine2: "Coherent",
      titleAccent2: "System.",
      description: "Portfolio Nexus turns four separate projects into one guided case-study system. Each project keeps its own product story, while the portfolio gives them shared routing, multilingual content, static generation and a clearer engineering narrative.",
      hud: { status: "ONLINE", network: "4 CASES // INDEXED", latency: "SSG" },
      circularText: "CASE STUDY ECOSYSTEM - NEXUS - STATIC ROUTES - MULTILINGUAL -",
      coreOnline: "CORE ONLINE",
      nextLevel: "NEXT LEVEL: EVIDENCE",
      nodes: [
        { title: "Experience", subtitle: "Music Player", status: "LOCAL" },
        { title: "Learning", subtitle: "AI Tutor", status: "DESIGNED" },
        { title: "Control", subtitle: "SaaS Platform", status: "SECURE" },
        { title: "Evidence", subtitle: "Portfolio Nexus", status: "SSG" },
      ],
      flowSteps: ["Problem", "Decision", "Solution", "Evidence"],
    },
    digitalGap: {
      label: "PROBLEM",
      titleLine1: "Strong Projects.",
      titleLine2: "Fragmented Story.",
      description: "A technical portfolio can become a grid of disconnected cards: impressive visuals, scattered claims and little context about decisions. The challenge was to make the work readable as engineering, not just as presentation.",
      fragments: ["Separate Stories", "Mixed Claims", "Hidden Decisions", "Scattered Evidence", "Uneven Context"],
      fragmentStatus: "FRAGMENTED",
      manifestoWords: ["A", "portfolio", "should", "explain", "the", "work."],
      convergenceLabel: "CASE SYSTEM",
    },
    experience: {
      label: "CASE 01",
      titleLine1: "Experience.",
      titleLine2: "Local First.",
      description: "The Music Player case introduces the experience layer: personal libraries, playback state, native controls and interface polish organized around a local-first product direction.",
      features: ["Immersive UI", "Local Library", "Playback Flow", "Responsive Design"],
      manifestoLine1: "Music became the medium.",
      manifestoLine2: "Experience became the product question.",
    },
    intelligence: {
      label: "CASE 02",
      titleLine1: "Learning.",
      titleLine2: "Guided by Rules.",
      description: "The English Tutor case adds the intelligence layer: deterministic pedagogy shapes learning decisions before the AI response is written.",
      skills: ["Grammar", "Vocabulary", "Listening", "Speaking", "Writing"],
      insights: ["Teacher Brain", "AI Guidance", "Progress Tracking", "Pedagogical Feedback"],
      manifestoLine1: "Learning became structured.",
      manifestoLine2: "Intelligence became accountable.",
    },
    control: {
      label: "EVIDENCE",
      titleLine1: "Measured.",
      titleLine2: "Not Assumed.",
      cards: [
        { tag: "STATIC ROUTES", unit: "pages", description: "The current production build generates 14 static routes, including the project pages created from the registry.", status: "online", terminal: "npm run build" },
        { tag: "CASE REGISTRY", unit: "cases", description: "Four public cases are resolved from one registry, keeping the route generic and the case entries explicit.", status: "processing", terminal: "registry.resolve --slug", featured: true },
        { tag: "CONTENT SYSTEM", unit: "langs", description: "Public interface copy is maintained across PT, EN and ES message files instead of being scattered through page code.", status: "secure", terminal: "messages.sync --locales" },
      ],
    },
    evolution: {
      label: "NARRATIVE ARC",
      titleLine1: "From Screens.",
      titleLine2: "To Decisions.",
      description: "The portfolio now frames each project through the same lens: problem, engineering decision, solution, evidence and result. That structure makes the work easier to evaluate without overstating what has not been proven yet.",
      milestones: [
        { title: "Problem", year: "01", description: "Explain the real constraint behind each project." },
        { title: "Decision", year: "02", description: "Show the engineering choice and its trade-offs." },
        { title: "Solution", year: "03", description: "Connect architecture, UI and product behavior." },
        { title: "Evidence", year: "04", description: "Separate verified results from designed capabilities and targets." },
      ],
      manifesto: ["Problem", "Decision", "Solution", "Evidence"],
    },
    engineering: {
      label: "ENGINEERING DECISION",
      titleLine1: "A Registry",
      titleLine2: "Instead of Fallbacks",
      boot: "INITIALIZING NEXUS ARCHITECTURE...",
      description: "The central decision was to make projects flow through a registry. Routes stay generic, cases own their content and components, legacy slugs redirect to canonical entries, and public pages can be generated statically.",
      layers: [
        { title: "Routing Layer", technologies: ["Next.js App Router", "generateStaticParams", "notFound", "redirect"] },
        { title: "Registry Layer", technologies: ["projectsRegistry", "Canonical Slugs", "Dynamic Imports", "Typed Entries"] },
        { title: "Content Layer", technologies: ["PT", "EN", "ES", "Metadata"] },
        { title: "Motion Layer", technologies: ["GSAP", "Framer Motion", "Reduced Motion", "Cleanup"] },
        { title: "Deployment Layer", technologies: ["Static Export", "GitHub Pages", "Playwright", "CI"] },
      ],
      manifestoLine1: "The portfolio is not a pile of pages.",
      manifestoLine2: "It is a system for explaining work.",
    },
    design: {
      label: "SOLUTION",
      titleLine1: "Clarity",
      titleLine2: "With Motion.",
      descriptionLine1: "The visual system keeps the cinematic language, but the story now has a technical spine.",
      descriptionLine2: "Motion supports orientation, content is localized, claims are moderated and the project structure remains extensible.",
      principles: [
        { title: "Clarity", description: "Each case needs to explain the problem before presenting the solution." },
        { title: "Evidence", description: "Strong claims are tied to build output, tests, E2E, profiling or documentation." },
        { title: "Access", description: "Focus states and reduced motion keep the experience usable beyond the default path." },
        { title: "Performance", description: "Heavy sections can be deferred so the first viewport stays responsive." },
        { title: "Maintainability", description: "New cases should enter through the registry instead of route-specific fallbacks." },
      ],
      manifestoLine1: "Design gives the case energy.",
      manifestoLine2: "Structure gives it credibility.",
    },
    numbers: {
      label: "VERIFIED SIGNALS",
      titleLine1: "Evidence.",
      titleLine2: "In Context.",
      description: "The numbers shown here are limited to signals already visible in this repository or produced by the current validation flow.",
      stats: [
        { value: 4, suffix: "", label: "Cases", description: "Resolved through the public projects registry." },
        { value: 14, suffix: "", label: "Static Routes", description: "Generated by the current production build." },
        { value: 3, suffix: "", label: "Languages", description: "PT, EN and ES content paths are maintained." },
        { value: 8, suffix: "", label: "Unit Checks", description: "Current Vitest checks cover hooks, i18n and contact behavior." },
        { value: 3, suffix: "", label: "E2E Flows", description: "Core journeys run against the exported site." },
        { value: 1, suffix: "", label: "Deploy Path", description: "GitHub Pages static export is prepared for the repository subpath." },
      ],
      manifestoLine1: "Evidence is more useful than volume.",
      manifestoLine2: "Context makes it trustworthy.",
    },
    future: {
      label: "NEXT STEP",
      titleLine1: "EVIDENCE IS",
      titleLine2: "THE NEXT LAYER.",
      descriptionLine1: "The narrative is now structured. The next step is to attach deeper proof to each project.",
      descriptionLine2: "Tests, diagrams, profiling notes and claim registers turn presentation into technical trust.",
      orbitItems: ["Case Evidence", "Architecture Diagrams", "Performance Notes", "Accessibility Checks", "CI Records", "Trade-offs", "Project READMEs"],
      circularText: "EVIDENCE LAYER - NEXUS CORE - TECHNICAL TRUST -",
      coreOnline: "CORE ONLINE",
      manifesto: [
        "The work starts with projects.",
        "It becomes stronger through structure.",
        "It becomes credible through evidence.",
        "It becomes memorable through clarity.",
      ],
      manifestoStrong: "The next chapter is documentation that proves the story.",
      status: "Evidence In Progress",
    },
    final: {
      label: "FINAL CHAPTER",
      titleLines: ["LET'S BUILD", "WITH", "CLARITY."],
      descriptionLine1: "From separate projects to a coherent engineering narrative.",
      descriptionLine2: "The next product conversation can start from evidence, not guesswork.",
      status: "Evidence In Progress",
      pillars: ["Problem", "Decision", "Solution", "Evidence"],
    },
  },
  pt: {
    hero: {
      label: "ATO IV",
      titleLine1: "QUATRO",
      titleAccent1: "CASES.",
      titleLine2: "UM",
      titleAccent2: "SISTEMA.",
      descriptionStart: "Um ecossistema de cases conectando",
      domains: ["experiência", "aprendizado", "produtividade", "evidência"],
    },
    connected: {
      label: "RESULTADO",
      titleLine1: "Cases",
      titleAccent1: "Conectados.",
      titleLine2: "Sistema",
      titleAccent2: "Coerente.",
      description: "O Portfolio Nexus transforma quatro projetos separados em um sistema guiado de estudos de caso. Cada projeto mantém sua própria história de produto, enquanto o portfólio oferece rotas compartilhadas, conteúdo multilíngue, geração estática e uma narrativa de engenharia mais clara.",
      hud: { status: "ONLINE", network: "4 CASES // INDEXED", latency: "SSG" },
      circularText: "ECOSSISTEMA DE CASES - NEXUS - ROTAS ESTÁTICAS - MULTILÍNGUE -",
      coreOnline: "CORE ONLINE",
      nextLevel: "PRÓXIMO NÍVEL: EVIDÊNCIA",
      nodes: [
        { title: "Experiência", subtitle: "Music Player", status: "LOCAL" },
        { title: "Aprendizado", subtitle: "AI Tutor", status: "DESIGNED" },
        { title: "Controle", subtitle: "Plataforma SaaS", status: "SEGURO" },
        { title: "Evidência", subtitle: "Portfolio Nexus", status: "SSG" },
      ],
      flowSteps: ["Problema", "Decisão", "Solução", "Evidência"],
    },
    digitalGap: {
      label: "PROBLEMA",
      titleLine1: "Projetos Fortes.",
      titleLine2: "História Fragmentada.",
      description: "Um portfólio técnico pode virar uma grade de cards desconectados: visual forte, claims espalhados e pouco contexto sobre decisões. O desafio era tornar o trabalho legível como engenharia, não apenas como apresentação.",
      fragments: ["Histórias Separadas", "Claims Misturados", "Decisões Ocultas", "Evidências Espalhadas", "Contexto Desigual"],
      fragmentStatus: "FRAGMENTADO",
      manifestoWords: ["Um", "portfólio", "deve", "explicar", "o", "trabalho."],
      convergenceLabel: "SISTEMA DE CASES",
    },
    experience: {
      label: "CASE 01",
      titleLine1: "Experiência.",
      titleLine2: "Local First.",
      description: "O case Music Player apresenta a camada de experiência: bibliotecas pessoais, estado de reprodução, controles nativos e polimento de interface organizados em torno de uma direção local-first.",
      features: ["UI Imersiva", "Biblioteca Local", "Fluxo de Reprodução", "Design Responsivo"],
      manifestoLine1: "A música virou o meio.",
      manifestoLine2: "A experiência virou a pergunta de produto.",
    },
    intelligence: {
      label: "CASE 02",
      titleLine1: "Aprendizado.",
      titleLine2: "Guiado por Regras.",
      description: "O case English Tutor adiciona a camada de inteligência: a pedagogia determinística orienta decisões de aprendizado antes da resposta da IA ser escrita.",
      skills: ["Gramática", "Vocabulário", "Escuta", "Fala", "Escrita"],
      insights: ["Teacher Brain", "Orientação por IA", "Progresso", "Feedback Pedagógico"],
      manifestoLine1: "O aprendizado ficou estruturado.",
      manifestoLine2: "A inteligência ficou responsável.",
    },
    control: {
      label: "EVIDÊNCIA",
      titleLine1: "Medido.",
      titleLine2: "Não Presumido.",
      cards: [
        { tag: "ROTAS ESTÁTICAS", unit: "pages", description: "O build atual de produção gera 14 rotas estáticas, incluindo páginas de projetos criadas a partir do registry.", status: "online", terminal: "npm run build" },
        { tag: "REGISTRY DE CASES", unit: "cases", description: "Quatro cases públicos são resolvidos por um único registry, mantendo a rota genérica e as entradas explícitas.", status: "processing", terminal: "registry.resolve --slug", featured: true },
        { tag: "SISTEMA DE CONTEÚDO", unit: "langs", description: "A cópia pública da interface é mantida em arquivos PT, EN e ES em vez de ficar espalhada no código das páginas.", status: "secure", terminal: "messages.sync --locales" },
      ],
    },
    evolution: {
      label: "ARCO NARRATIVO",
      titleLine1: "De Telas.",
      titleLine2: "Para Decisões.",
      description: "O portfólio agora enquadra cada projeto pela mesma lente: problema, decisão de engenharia, solução, evidência e resultado. Essa estrutura facilita avaliar o trabalho sem exagerar o que ainda não foi comprovado.",
      milestones: [
        { title: "Problema", year: "01", description: "Explicar a restrição real por trás de cada projeto." },
        { title: "Decisão", year: "02", description: "Mostrar a escolha de engenharia e seus trade-offs." },
        { title: "Solução", year: "03", description: "Conectar arquitetura, UI e comportamento de produto." },
        { title: "Evidência", year: "04", description: "Separar resultados verificados de capacidades projetadas e metas." },
      ],
      manifesto: ["Problema", "Decisão", "Solução", "Evidência"],
    },
    engineering: {
      label: "DECISÃO DE ENGENHARIA",
      titleLine1: "Um Registry",
      titleLine2: "Em Vez de Fallbacks",
      boot: "INICIALIZANDO ARQUITETURA NEXUS...",
      description: "A decisão central foi fazer os projetos passarem por um registry. As rotas permanecem genéricas, os cases possuem conteúdo e componentes próprios, slugs antigos redirecionam para entradas canônicas e as páginas públicas podem ser geradas estaticamente.",
      layers: [
        { title: "Camada de Rotas", technologies: ["Next.js App Router", "generateStaticParams", "notFound", "redirect"] },
        { title: "Camada de Registry", technologies: ["projectsRegistry", "Slugs Canônicos", "Imports Dinâmicos", "Entradas Tipadas"] },
        { title: "Camada de Conteúdo", technologies: ["PT", "EN", "ES", "Metadata"] },
        { title: "Camada de Motion", technologies: ["GSAP", "Framer Motion", "Reduced Motion", "Cleanup"] },
        { title: "Camada de Deploy", technologies: ["Static Export", "GitHub Pages", "Playwright", "CI"] },
      ],
      manifestoLine1: "O portfólio não é uma pilha de páginas.",
      manifestoLine2: "É um sistema para explicar trabalho.",
    },
    design: {
      label: "SOLUÇÃO",
      titleLine1: "Clareza",
      titleLine2: "Com Movimento.",
      descriptionLine1: "O sistema visual mantém a linguagem cinematográfica, mas a história agora tem uma espinha técnica.",
      descriptionLine2: "Motion apoia orientação, o conteúdo é localizado, os claims são moderados e a estrutura de projetos permanece extensível.",
      principles: [
        { title: "Clareza", description: "Cada case precisa explicar o problema antes de apresentar a solução." },
        { title: "Evidência", description: "Claims fortes se conectam a build, testes, E2E, profiling ou documentação." },
        { title: "Acesso", description: "Foco visível e reduced motion mantêm a experiência utilizável fora do caminho padrão." },
        { title: "Performance", description: "Seções pesadas podem ser adiadas para manter a primeira dobra responsiva." },
        { title: "Manutenção", description: "Novos cases devem entrar pelo registry em vez de fallbacks específicos de rota." },
      ],
      manifestoLine1: "Design dá energia ao case.",
      manifestoLine2: "Estrutura dá credibilidade.",
    },
    numbers: {
      label: "SINAIS VERIFICADOS",
      titleLine1: "Evidência.",
      titleLine2: "Com Contexto.",
      description: "Os números exibidos aqui se limitam a sinais já visíveis neste repositório ou produzidos pelo fluxo atual de validação.",
      stats: [
        { value: 4, suffix: "", label: "Cases", description: "Resolvidos pelo registry público de projetos." },
        { value: 14, suffix: "", label: "Rotas Estáticas", description: "Geradas pelo build atual de produção." },
        { value: 3, suffix: "", label: "Idiomas", description: "PT, EN e ES mantidos nos caminhos de conteúdo." },
        { value: 8, suffix: "", label: "Testes Unitários", description: "Vitest cobre hooks, i18n e comportamento de contato." },
        { value: 3, suffix: "", label: "Fluxos E2E", description: "Jornadas centrais rodam contra o site exportado." },
        { value: 1, suffix: "", label: "Deploy Path", description: "Static export do GitHub Pages preparado para o subcaminho do repositório." },
      ],
      manifestoLine1: "Evidência importa mais que volume.",
      manifestoLine2: "Contexto torna o número confiável.",
    },
    future: {
      label: "PRÓXIMO PASSO",
      titleLine1: "EVIDÊNCIA É",
      titleLine2: "A PRÓXIMA CAMADA.",
      descriptionLine1: "A narrativa agora está estruturada. O próximo passo é anexar provas mais profundas a cada projeto.",
      descriptionLine2: "Testes, diagramas, notas de profiling e registros de claims transformam apresentação em confiança técnica.",
      orbitItems: ["Evidência de Case", "Diagramas de Arquitetura", "Notas de Performance", "Checagens de Acessibilidade", "Registros de CI", "Trade-offs", "READMEs dos Projetos"],
      circularText: "CAMADA DE EVIDÊNCIA - NEXUS CORE - CONFIANÇA TÉCNICA -",
      coreOnline: "CORE ONLINE",
      manifesto: [
        "O trabalho começa com projetos.",
        "Fica mais forte com estrutura.",
        "Fica crível com evidência.",
        "Fica memorável com clareza.",
      ],
      manifestoStrong: "O próximo capítulo é uma documentação que prova a história.",
      status: "Evidência em Progresso",
    },
    final: {
      label: "CAPÍTULO FINAL",
      titleLines: ["VAMOS CRIAR", "COM", "CLAREZA."],
      descriptionLine1: "De projetos separados para uma narrativa de engenharia coerente.",
      descriptionLine2: "A próxima conversa de produto pode começar por evidências, não por suposições.",
      status: "Evidência em Progresso",
      pillars: ["Problema", "Decisão", "Solução", "Evidência"],
    },
  },
  es: {
    hero: {
      label: "ACTO IV",
      titleLine1: "CUATRO",
      titleAccent1: "CASOS.",
      titleLine2: "UN",
      titleAccent2: "SISTEMA.",
      descriptionStart: "Un ecosistema de casos que conecta",
      domains: ["experiencia", "aprendizaje", "productividad", "evidencia"],
    },
    connected: {
      label: "RESULTADO",
      titleLine1: "Casos",
      titleAccent1: "Conectados.",
      titleLine2: "Sistema",
      titleAccent2: "Coherente.",
      description: "Portfolio Nexus transforma cuatro proyectos separados en un sistema guiado de estudios de caso. Cada proyecto mantiene su propia historia de producto, mientras el portfolio ofrece rutas compartidas, contenido multilingüe, generación estática y una narrativa de ingeniería más clara.",
      hud: { status: "ONLINE", network: "4 CASES // INDEXED", latency: "SSG" },
      circularText: "ECOSISTEMA DE CASOS - NEXUS - RUTAS ESTÁTICAS - MULTILINGÜE -",
      coreOnline: "CORE ONLINE",
      nextLevel: "PRÓXIMO NIVEL: EVIDENCIA",
      nodes: [
        { title: "Experiencia", subtitle: "Music Player", status: "LOCAL" },
        { title: "Aprendizaje", subtitle: "AI Tutor", status: "DESIGNED" },
        { title: "Control", subtitle: "Plataforma SaaS", status: "SEGURO" },
        { title: "Evidencia", subtitle: "Portfolio Nexus", status: "SSG" },
      ],
      flowSteps: ["Problema", "Decisión", "Solución", "Evidencia"],
    },
    digitalGap: {
      label: "PROBLEMA",
      titleLine1: "Proyectos Fuertes.",
      titleLine2: "Historia Fragmentada.",
      description: "Un portfolio técnico puede convertirse en una grilla de cards desconectados: visual fuerte, claims dispersos y poco contexto sobre decisiones. El desafío era hacer que el trabajo se leyera como ingeniería, no solo como presentación.",
      fragments: ["Historias Separadas", "Claims Mezclados", "Decisiones Ocultas", "Evidencias Dispersas", "Contexto Desigual"],
      fragmentStatus: "FRAGMENTADO",
      manifestoWords: ["Un", "portfolio", "debe", "explicar", "el", "trabajo."],
      convergenceLabel: "SISTEMA DE CASOS",
    },
    experience: {
      label: "CASO 01",
      titleLine1: "Experiencia.",
      titleLine2: "Local First.",
      description: "El caso Music Player presenta la capa de experiencia: bibliotecas personales, estado de reproducción, controles nativos y pulido de interfaz organizados alrededor de una dirección local-first.",
      features: ["UI Inmersiva", "Biblioteca Local", "Flujo de Reproducción", "Diseño Responsivo"],
      manifestoLine1: "La música se volvió el medio.",
      manifestoLine2: "La experiencia se volvió la pregunta de producto.",
    },
    intelligence: {
      label: "CASO 02",
      titleLine1: "Aprendizaje.",
      titleLine2: "Guiado por Reglas.",
      description: "El caso English Tutor agrega la capa de inteligencia: la pedagogía determinística orienta decisiones de aprendizaje antes de que la respuesta de IA sea escrita.",
      skills: ["Gramática", "Vocabulario", "Escucha", "Habla", "Escritura"],
      insights: ["Teacher Brain", "Guía con IA", "Progreso", "Feedback Pedagógico"],
      manifestoLine1: "El aprendizaje quedó estructurado.",
      manifestoLine2: "La inteligencia quedó responsable.",
    },
    control: {
      label: "EVIDENCIA",
      titleLine1: "Medido.",
      titleLine2: "No Supuesto.",
      cards: [
        { tag: "RUTAS ESTÁTICAS", unit: "pages", description: "El build actual de producción genera 14 rutas estáticas, incluyendo páginas de proyectos creadas desde el registry.", status: "online", terminal: "npm run build" },
        { tag: "REGISTRY DE CASOS", unit: "cases", description: "Cuatro casos públicos se resuelven desde un único registry, manteniendo la ruta genérica y las entradas explícitas.", status: "processing", terminal: "registry.resolve --slug", featured: true },
        { tag: "SISTEMA DE CONTENIDO", unit: "langs", description: "La copia pública de la interfaz se mantiene en archivos PT, EN y ES en vez de quedar dispersa en el código de páginas.", status: "secure", terminal: "messages.sync --locales" },
      ],
    },
    evolution: {
      label: "ARCO NARRATIVO",
      titleLine1: "De Pantallas.",
      titleLine2: "A Decisiones.",
      description: "El portfolio ahora encuadra cada proyecto con la misma lente: problema, decisión de ingeniería, solución, evidencia y resultado. Esa estructura facilita evaluar el trabajo sin exagerar lo que aún no fue comprobado.",
      milestones: [
        { title: "Problema", year: "01", description: "Explicar la restricción real detrás de cada proyecto." },
        { title: "Decisión", year: "02", description: "Mostrar la elección de ingeniería y sus trade-offs." },
        { title: "Solución", year: "03", description: "Conectar arquitectura, UI y comportamiento de producto." },
        { title: "Evidencia", year: "04", description: "Separar resultados verificados de capacidades diseñadas y metas." },
      ],
      manifesto: ["Problema", "Decisión", "Solución", "Evidencia"],
    },
    engineering: {
      label: "DECISIÓN DE INGENIERÍA",
      titleLine1: "Un Registry",
      titleLine2: "En Lugar de Fallbacks",
      boot: "INICIALIZANDO ARQUITECTURA NEXUS...",
      description: "La decisión central fue hacer que los proyectos pasen por un registry. Las rutas permanecen genéricas, los casos poseen contenido y componentes propios, los slugs antiguos redireccionan a entradas canónicas y las páginas públicas pueden generarse estáticamente.",
      layers: [
        { title: "Capa de Rutas", technologies: ["Next.js App Router", "generateStaticParams", "notFound", "redirect"] },
        { title: "Capa de Registry", technologies: ["projectsRegistry", "Slugs Canónicos", "Imports Dinámicos", "Entradas Tipadas"] },
        { title: "Capa de Contenido", technologies: ["PT", "EN", "ES", "Metadata"] },
        { title: "Capa de Motion", technologies: ["GSAP", "Framer Motion", "Reduced Motion", "Cleanup"] },
        { title: "Capa de Deploy", technologies: ["Static Export", "GitHub Pages", "Playwright", "CI"] },
      ],
      manifestoLine1: "El portfolio no es una pila de páginas.",
      manifestoLine2: "Es un sistema para explicar trabajo.",
    },
    design: {
      label: "SOLUCIÓN",
      titleLine1: "Claridad",
      titleLine2: "Con Movimiento.",
      descriptionLine1: "El sistema visual mantiene el lenguaje cinematográfico, pero la historia ahora tiene una columna técnica.",
      descriptionLine2: "Motion apoya orientación, el contenido está localizado, los claims están moderados y la estructura de proyectos sigue siendo extensible.",
      principles: [
        { title: "Claridad", description: "Cada caso debe explicar el problema antes de presentar la solución." },
        { title: "Evidencia", description: "Claims fuertes se conectan a build, tests, E2E, profiling o documentación." },
        { title: "Acceso", description: "Foco visible y reduced motion mantienen la experiencia usable fuera del camino estándar." },
        { title: "Rendimiento", description: "Secciones pesadas pueden diferirse para mantener el primer viewport responsivo." },
        { title: "Mantenimiento", description: "Nuevos casos deben entrar por el registry en vez de fallbacks específicos de ruta." },
      ],
      manifestoLine1: "El diseño da energía al caso.",
      manifestoLine2: "La estructura le da credibilidad.",
    },
    numbers: {
      label: "SEÑALES VERIFICADAS",
      titleLine1: "Evidencia.",
      titleLine2: "Con Contexto.",
      description: "Los números mostrados aquí se limitan a señales ya visibles en este repositorio o producidas por el flujo actual de validación.",
      stats: [
        { value: 4, suffix: "", label: "Casos", description: "Resueltos por el registry público de proyectos." },
        { value: 14, suffix: "", label: "Rutas Estáticas", description: "Generadas por el build actual de producción." },
        { value: 3, suffix: "", label: "Idiomas", description: "PT, EN y ES mantenidos en los caminos de contenido." },
        { value: 8, suffix: "", label: "Tests Unitarios", description: "Vitest cubre hooks, i18n y comportamiento de contacto." },
        { value: 3, suffix: "", label: "Flujos E2E", description: "Jornadas centrales corren contra el sitio exportado." },
        { value: 1, suffix: "", label: "Deploy Path", description: "Static export de GitHub Pages preparado para el subcamino del repositorio." },
      ],
      manifestoLine1: "La evidencia importa más que el volumen.",
      manifestoLine2: "El contexto vuelve confiable el número.",
    },
    future: {
      label: "PRÓXIMO PASO",
      titleLine1: "EVIDENCIA ES",
      titleLine2: "LA PRÓXIMA CAPA.",
      descriptionLine1: "La narrativa ahora está estructurada. El próximo paso es anexar pruebas más profundas a cada proyecto.",
      descriptionLine2: "Tests, diagramas, notas de profiling y registros de claims transforman presentación en confianza técnica.",
      orbitItems: ["Evidencia de Caso", "Diagramas de Arquitectura", "Notas de Rendimiento", "Checks de Accesibilidad", "Registros de CI", "Trade-offs", "READMEs de Proyectos"],
      circularText: "CAPA DE EVIDENCIA - NEXUS CORE - CONFIANZA TÉCNICA -",
      coreOnline: "CORE ONLINE",
      manifesto: [
        "El trabajo empieza con proyectos.",
        "Se vuelve más fuerte con estructura.",
        "Se vuelve creíble con evidencia.",
        "Se vuelve memorable con claridad.",
      ],
      manifestoStrong: "El próximo capítulo es documentación que prueba la historia.",
      status: "Evidencia en Progreso",
    },
    final: {
      label: "CAPÍTULO FINAL",
      titleLines: ["VAMOS A CREAR", "CON", "CLARIDAD."],
      descriptionLine1: "De proyectos separados a una narrativa de ingeniería coherente.",
      descriptionLine2: "La próxima conversación de producto puede empezar por evidencias, no por suposiciones.",
      status: "Evidencia en Progreso",
      pillars: ["Problema", "Decisión", "Solución", "Evidencia"],
    },
  },
} as const;