export const ecosystemContent = {
  en: {
    hero: {
      label: "ACT IV",
      titleLine1: "FOUR",
      titleAccent1: "PRODUCTS.",
      titleLine2: "ONE",
      titleAccent2: "VISION.",
      descriptionStart: "A digital ecosystem connecting",
      domains: ["entertainment", "learning", "productivity", "innovation"],
    },
    connected: {
      label: "THE ECOSYSTEM",
      titleLine1: "Connected",
      titleAccent1: "Worlds.",
      titleLine2: "Unified",
      titleAccent2: "Vision.",
      description: "Each project explores a different product problem: listening, learning, productivity and personal presentation. Together they form a portfolio that shows growth across interface craft, application architecture and engineering judgment.",
      hud: { status: "ONLINE", network: "4 CASES // INDEXED", latency: "SSG" },
      circularText: "CASE STUDY ECOSYSTEM - NEXUS - STATIC ROUTES - MULTILINGUAL -",
      coreOnline: "CORE ONLINE",
      nextLevel: "NEXT LEVEL: EVOLUTION",
      nodes: [
        { title: "Experience", subtitle: "Music Player", status: "LOCAL" },
        { title: "Intelligence", subtitle: "AI Tutor", status: "ADAPTIVE" },
        { title: "Control", subtitle: "SaaS Platform", status: "SECURE" },
        { title: "Vision", subtitle: "Portfolio Nexus", status: "SSG" },
      ],
      flowSteps: ["Experience", "Intelligence", "Control", "Vision"],
    },
    digitalGap: {
      label: "THE DIGITAL GAP",
      titleLine1: "Powerful Tools.",
      titleLine2: "Fragmented Experiences.",
      description: "A portfolio can easily become a grid of unrelated cards. Portfolio Nexus turns those projects into a guided narrative where each case explains a problem, a decision and a product direction.",
      fragments: ["Different Tools", "Different Workflows", "Different Platforms", "Different Systems", "Different Ecosystems"],
      fragmentStatus: "DISCONNECTED",
      manifestoWords: ["We", "believe", "there", "is", "a", "better", "way."],
      convergenceLabel: "ECOSYSTEM",
    },
    experience: {
      label: "EXPERIENCE",
      titleLine1: "Experience.",
      titleLine2: "Reimagined.",
      description: "A local-first music player that treats personal libraries, playback state, native controls and interface polish as one listening experience.",
      features: ["Immersive UI", "Audio Visualization", "Modern Interactions", "Responsive Design"],
      manifestoLine1: "Music became the medium.",
      manifestoLine2: "Experience became the product.",
    },
    intelligence: {
      label: "INTELLIGENCE",
      titleLine1: "Intelligence.",
      titleLine2: "Personalized.",
      description: "A language tutor where deterministic pedagogy shapes the conversation before the AI response is written.",
      skills: ["Grammar", "Vocabulary", "Listening", "Speaking", "Writing"],
      insights: ["Adaptive Learning", "AI Guidance", "Progress Tracking", "Personalized Feedback"],
      manifestoLine1: "Learning became personal.",
      manifestoLine2: "Intelligence became adaptive.",
    },
    control: {
      label: "MISSION CONTROL",
      titleLine1: "Control.",
      titleLine2: "At Scale.",
      cards: [
        { tag: "STATIC ROUTES", unit: "SSG", description: "Project pages are generated from the registry, keeping the public case system predictable and easy to extend.", status: "online", terminal: "next.build --routes" },
        { tag: "CASE REGISTRY", unit: "IDX", description: "Each project owns its content and component entry point while the route stays generic.", status: "processing", terminal: "registry.resolve --slug", featured: true },
        { tag: "CONTENT SYSTEM", unit: "I18N", description: "The portfolio speaks through PT, EN and ES content files instead of hardcoded page copy.", status: "secure", terminal: "messages.sync --locales" },
      ],
    },
    evolution: {
      label: "EVOLUTION",
      titleLine1: "From Products.",
      titleLine2: "To Ecosystems.",
      description: "Each project expanded the scope, complexity and ambition of the journey. Together they reveal a continuous evolution in product thinking, engineering and digital experiences.",
      milestones: [
        { title: "Experience", year: "2024", description: "Creating memorable interfaces. Designing interactions. Building emotional experiences." },
        { title: "Intelligence", year: "2025", description: "Introducing AI. Personalizing learning. Creating adaptive systems." },
        { title: "Control", year: "2025", description: "Scaling complexity. Managing data. Building business platforms." },
        { title: "Vision", year: "2026", description: "Connecting products. Building ecosystems. Designing the future." },
      ],
      manifesto: ["From Experiences", "To Intelligence", "To Systems", "To Ecosystems"],
    },
    engineering: {
      label: "ENGINEERING DNA",
      titleLine1: "Engineered",
      titleLine2: "For Experiences",
      boot: "INITIALIZING NEXUS ARCHITECTURE...",
      description: "The portfolio is built as a modular case system: Next.js routes, project registry, reusable effects, localized content and visual sections working together.",
      layers: [
        { title: "Experience Layer", technologies: ["React", "Next.js", "GSAP", "Framer Motion"] },
        { title: "Intelligence Layer", technologies: ["Teacher Brain", "FastAPI", "Local LLM", "Pedagogy"] },
        { title: "Application Layer", technologies: ["Spring Boot", "REST APIs", "Architecture", "Business Logic"] },
        { title: "Data Layer", technologies: ["PostgreSQL", "Analytics", "Persistence", "Modeling"] },
        { title: "Deployment Layer", technologies: ["Docker", "Cloud", "CI/CD", "Scalability"] },
      ],
      manifestoLine1: "Technology is not the destination.",
      manifestoLine2: "It is the foundation.",
    },
    design: {
      label: "DESIGN PHILOSOPHY",
      titleLine1: "Crafted",
      titleLine2: "With Purpose.",
      descriptionLine1: "Every interaction, animation and detail exists for a reason.",
      descriptionLine2: "Design is not decoration. It is how products communicate, guide and inspire.",
      principles: [
        { title: "Motion", description: "Movement guides attention and creates natural digital experiences." },
        { title: "Clarity", description: "Complex systems should feel intuitive, simple and effortless." },
        { title: "Performance", description: "Speed is not a feature. It is part of the experience." },
        { title: "Details", description: "Small interactions create memorable moments." },
        { title: "Craftsmanship", description: "Every pixel deserves intention, precision and care." },
      ],
      manifestoLine1: "Beautiful products are not created by accident.",
      manifestoLine2: "They are crafted with purpose.",
    },
    numbers: {
      label: "BY THE NUMBERS",
      titleLine1: "Impact.",
      titleLine2: "At Scale.",
      description: "Behind the visual experience is a portfolio architecture built to present real projects with clearer context, stronger navigation and room for deeper case studies.",
      stats: [
        { value: 4, suffix: "", label: "Products", description: "Connected through a unified ecosystem." },
        { value: 14, suffix: "", label: "Static Pages", description: "Generated in the production build." },
        { value: 3, suffix: "", label: "Languages", description: "Content experience available in PT, EN and ES." },
        { value: 8, suffix: "", label: "Tests", description: "Current automated checks covering hooks, i18n and contact flow." },
        { value: 10, suffix: "+", label: "Technologies", description: "Working together across the stack." },
        { value: 1, suffix: "", label: "Ecosystem", description: "One vision connecting everything." },
      ],
      manifestoLine1: "Every number tells a story.",
      manifestoLine2: "Together they reveal an ecosystem.",
    },
    future: {
      label: "THE FUTURE",
      titleLine1: "THIS IS ONLY",
      titleLine2: "THE BEGINNING.",
      descriptionLine1: "Building products. Connecting systems. Designing experiences.",
      descriptionLine2: "Creating the future, one line of code at a time.",
      orbitItems: ["Artificial Intelligence", "Cloud Systems", "Automation", "Mobile Experiences", "Design Systems", "Data Platforms", "Product Innovation"],
      circularText: "FUTURE VISION • NEXUS CORE • INFINITE POSSIBILITIES •",
      coreOnline: "CORE ONLINE",
      manifesto: [
        "The journey started with experiences.",
        "It evolved through intelligence.",
        "It scaled through systems.",
        "Now it moves toward ecosystems.",
      ],
      manifestoStrong: "The next chapter is already being written.",
      status: "Future In Progress",
    },
    final: {
      label: "FINAL CHAPTER",
      titleLines: ["LET'S BUILD", "SOMETHING", "REMARKABLE."],
      descriptionLine1: "From ideas to ecosystems. From concepts to products.",
      descriptionLine2: "Let's create the next chapter together.",
      status: "Future In Progress",
      pillars: ["Experience", "Intelligence", "Control", "Vision"],
    },
  },
  pt: {
    hero: {
      label: "ATO IV",
      titleLine1: "QUATRO",
      titleAccent1: "PRODUTOS.",
      titleLine2: "UMA",
      titleAccent2: "VISÃO.",
      descriptionStart: "Um ecossistema digital conectando",
      domains: ["entretenimento", "aprendizado", "produtividade", "inovação"],
    },
    connected: {
      label: "O ECOSSISTEMA",
      titleLine1: "Mundos",
      titleAccent1: "Conectados.",
      titleLine2: "Visão",
      titleAccent2: "Unificada.",
      description: "Cada produto explora uma dimensão diferente da experiência digital. Juntos, formam um ecossistema conectado de entretenimento, inteligência, produtividade e inovação, sincronizado em tempo real.",
      hud: { status: "ONLINE", network: "4 CASES // INDEXED", latency: "SSG" },
      circularText: "ECOSSISTEMA DE CASES - NEXUS - ROTAS ESTATICAS - MULTILINGUE -",
      coreOnline: "CORE ONLINE",
      nextLevel: "PRÓXIMO NÍVEL: EVOLUÇÃO",
      nodes: [
        { title: "Experiência", subtitle: "Music Player", status: "AO VIVO" },
        { title: "Inteligência", subtitle: "AI Tutor", status: "ATIVO" },
        { title: "Controle", subtitle: "Plataforma SaaS", status: "ONLINE" },
        { title: "Visão", subtitle: "Portfolio Nexus", status: "SSG" },
      ],
      flowSteps: ["Experiência", "Inteligência", "Controle", "Visão"],
    },
    digitalGap: {
      label: "A LACUNA DIGITAL",
      titleLine1: "Ferramentas Poderosas.",
      titleLine2: "Experiências Fragmentadas.",
      description: "Produtos modernos resolvem problemas individuais. Ainda assim, muitas experiências digitais seguem desconectadas. A tecnologia ficou mais poderosa, mas não necessariamente mais unificada.",
      fragments: ["Ferramentas Diferentes", "Fluxos Diferentes", "Plataformas Diferentes", "Sistemas Diferentes", "Ecossistemas Diferentes"],
      fragmentStatus: "DESCONECTADO",
      manifestoWords: ["Nós", "acreditamos", "que", "existe", "um", "caminho", "melhor."],
      convergenceLabel: "ECOSSISTEMA",
    },
    experience: {
      label: "EXPERIÊNCIA",
      titleLine1: "Experiência.",
      titleLine2: "Reimaginada.",
      description: "Mais que um player de música. Uma experiência digital imersiva construída com movimento, interação e emoção.",
      features: ["UI Imersiva", "Visualização de Áudio", "Interações Modernas", "Design Responsivo"],
      manifestoLine1: "A música virou o meio.",
      manifestoLine2: "A experiência virou o produto.",
    },
    intelligence: {
      label: "INTELIGÊNCIA",
      titleLine1: "Inteligência.",
      titleLine2: "Personalizada.",
      description: "Uma experiência adaptativa de aprendizado criada para entender progresso, identificar fraquezas e guiar crescimento.",
      skills: ["Gramática", "Vocabulário", "Escuta", "Fala", "Escrita"],
      insights: ["Aprendizado Adaptativo", "Orientação por IA", "Acompanhamento de Progresso", "Feedback Personalizado"],
      manifestoLine1: "O aprendizado se tornou pessoal.",
      manifestoLine2: "A inteligência se tornou adaptativa.",
    },
    control: {
      label: "CONTROLE DE MISSÃO",
      titleLine1: "Controle.",
      titleLine2: "Em Escala.",
      cards: [
        { tag: "ROTAS ESTATICAS", unit: "pages", description: "As paginas de projeto nascem do registry, mantendo o sistema de cases previsivel e facil de expandir.", status: "online", terminal: "next.build --routes" },
        { tag: "REGISTRY DE CASES", unit: "cases", description: "Cada projeto possui conteudo e entrada de componente propria enquanto a rota continua generica.", status: "processing", terminal: "registry.resolve --slug", featured: true },
        { tag: "SISTEMA DE CONTEUDO", unit: "langs", description: "O portfolio fala por arquivos PT, EN e ES em vez de texto hardcoded em paginas.", status: "secure", terminal: "messages.sync --locales" },
      ],
    },
    evolution: {
      label: "EVOLUÇÃO",
      titleLine1: "De Produtos.",
      titleLine2: "Para Ecossistemas.",
      description: "Cada projeto expandiu o escopo, a complexidade e a ambição da jornada. Juntos, revelam uma evolução contínua em produto, engenharia e experiências digitais.",
      milestones: [
        { title: "Experiência", year: "2024", description: "Criando interfaces memoráveis. Desenhando interações. Construindo experiências emocionais." },
        { title: "Inteligência", year: "2025", description: "Introduzindo IA. Personalizando aprendizado. Criando sistemas adaptativos." },
        { title: "Controle", year: "2025", description: "Escalando complexidade. Gerenciando dados. Construindo plataformas de negócio." },
        { title: "Visão", year: "2026", description: "Conectando produtos. Construindo ecossistemas. Desenhando o futuro." },
      ],
      manifesto: ["De Experiências", "Para Inteligência", "Para Sistemas", "Para Ecossistemas"],
    },
    engineering: {
      label: "DNA DE ENGENHARIA",
      titleLine1: "Projetado",
      titleLine2: "Para Experiências",
      boot: "INICIALIZANDO ARQUITETURA NEXUS...",
      description: "Cada produto nasce sobre uma arquitetura viva onde inteligência, engenharia e sistemas escaláveis convergem em um único ecossistema.",
      layers: [
        { title: "Camada de Experiência", technologies: ["React", "Next.js", "GSAP", "Framer Motion"] },
        { title: "Camada de Inteligência", technologies: ["Sistemas de IA", "Prompt Engineering", "OpenAI", "Automação"] },
        { title: "Camada de Aplicação", technologies: ["Spring Boot", "REST APIs", "Arquitetura", "Lógica de Negócio"] },
        { title: "Camada de Dados", technologies: ["PostgreSQL", "Analytics", "Persistência", "Modelagem"] },
        { title: "Camada de Deploy", technologies: ["Docker", "Cloud", "CI/CD", "Escalabilidade"] },
      ],
      manifestoLine1: "Tecnologia não é o destino.",
      manifestoLine2: "É a fundação.",
    },
    design: {
      label: "FILOSOFIA DE DESIGN",
      titleLine1: "Criado",
      titleLine2: "Com Propósito.",
      descriptionLine1: "Cada interação, animação e detalhe existe por um motivo.",
      descriptionLine2: "Design não é decoração. É como produtos comunicam, guiam e inspiram.",
      principles: [
        { title: "Movimento", description: "O movimento guia a atenção e cria experiências digitais naturais." },
        { title: "Clareza", description: "Sistemas complexos devem parecer intuitivos, simples e leves." },
        { title: "Performance", description: "Velocidade não é uma feature. É parte da experiência." },
        { title: "Detalhes", description: "Pequenas interações criam momentos memoráveis." },
        { title: "Artesania", description: "Cada pixel merece intenção, precisão e cuidado." },
      ],
      manifestoLine1: "Produtos bonitos não surgem por acidente.",
      manifestoLine2: "Eles são criados com propósito.",
    },
    numbers: {
      label: "EM NÚMEROS",
      titleLine1: "Impacto.",
      titleLine2: "Em Escala.",
      description: "Por trás de cada experiência existe um ecossistema crescente de produtos, sistemas, interações e ideias.",
      stats: [
        { value: 4, suffix: "", label: "Produtos", description: "Conectados por um ecossistema unificado." },
        { value: 150, suffix: "+", label: "Componentes", description: "Criados para construir experiências escaláveis." },
        { value: 100, suffix: "+", label: "Animações", description: "Desenhadas para fortalecer interação e narrativa." },
        { value: 30, suffix: "+", label: "Funcionalidades", description: "Em produtividade, aprendizado e entretenimento." },
        { value: 10, suffix: "+", label: "Tecnologias", description: "Trabalhando juntas ao longo da stack." },
        { value: 1, suffix: "", label: "Ecossistema", description: "Uma visão conectando tudo." },
      ],
      manifestoLine1: "Cada número conta uma história.",
      manifestoLine2: "Juntos, eles revelam um ecossistema.",
    },
    future: {
      label: "O FUTURO",
      titleLine1: "ISSO É SÓ",
      titleLine2: "O COMEÇO.",
      descriptionLine1: "Construindo produtos. Conectando sistemas. Desenhando experiências.",
      descriptionLine2: "Criando o futuro, uma linha de código por vez.",
      orbitItems: ["Inteligência Artificial", "Sistemas Cloud", "Automação", "Experiências Mobile", "Design Systems", "Plataformas de Dados", "Inovação em Produto"],
      circularText: "VISÃO FUTURA • NEXUS CORE • POSSIBILIDADES INFINITAS •",
      coreOnline: "CORE ONLINE",
      manifesto: [
        "A jornada começou com experiências.",
        "Evoluiu por meio da inteligência.",
        "Escalou através de sistemas.",
        "Agora caminha para ecossistemas.",
      ],
      manifestoStrong: "O próximo capítulo já está sendo escrito.",
      status: "Futuro em Progresso",
    },
    final: {
      label: "CAPÍTULO FINAL",
      titleLines: ["VAMOS CRIAR", "ALGO", "MARCANTE."],
      descriptionLine1: "De ideias a ecossistemas. De conceitos a produtos.",
      descriptionLine2: "Vamos criar o próximo capítulo juntos.",
      status: "Futuro em Progresso",
      pillars: ["Experiência", "Inteligência", "Controle", "Visão"],
    },
  },
  es: {
    hero: {
      label: "ACTO IV",
      titleLine1: "CUATRO",
      titleAccent1: "PRODUCTOS.",
      titleLine2: "UNA",
      titleAccent2: "VISIÓN.",
      descriptionStart: "Un ecosistema digital que conecta",
      domains: ["entretenimiento", "aprendizaje", "productividad", "innovación"],
    },
    connected: {
      label: "EL ECOSISTEMA",
      titleLine1: "Mundos",
      titleAccent1: "Conectados.",
      titleLine2: "Visión",
      titleAccent2: "Unificada.",
      description: "Cada producto explora una dimensión diferente de la experiencia digital. Juntos forman un ecosistema conectado de entretenimiento, inteligencia, productividad e innovación, sincronizado en tiempo real.",
      hud: { status: "ONLINE", network: "4 CASES // INDEXED", latency: "SSG" },
      circularText: "ECOSISTEMA DE CASOS - NEXUS - RUTAS ESTATICAS - MULTILINGUE -",
      coreOnline: "CORE ONLINE",
      nextLevel: "PRÓXIMO NIVEL: EVOLUCIÓN",
      nodes: [
        { title: "Experiencia", subtitle: "Music Player", status: "EN VIVO" },
        { title: "Inteligencia", subtitle: "AI Tutor", status: "ACTIVO" },
        { title: "Control", subtitle: "Plataforma SaaS", status: "ONLINE" },
        { title: "Visión", subtitle: "Portfolio Nexus", status: "SSG" },
      ],
      flowSteps: ["Experiencia", "Inteligencia", "Control", "Visión"],
    },
    digitalGap: {
      label: "LA BRECHA DIGITAL",
      titleLine1: "Herramientas Poderosas.",
      titleLine2: "Experiencias Fragmentadas.",
      description: "Los productos modernos resuelven problemas individuales. Aun así, muchas experiencias digitales siguen desconectadas. La tecnología se volvió más poderosa, pero no necesariamente más unificada.",
      fragments: ["Herramientas Diferentes", "Flujos Diferentes", "Plataformas Diferentes", "Sistemas Diferentes", "Ecosistemas Diferentes"],
      fragmentStatus: "DESCONECTADO",
      manifestoWords: ["Creemos", "que", "existe", "un", "camino", "mejor."],
      convergenceLabel: "ECOSISTEMA",
    },
    experience: {
      label: "EXPERIENCIA",
      titleLine1: "Experiencia.",
      titleLine2: "Reimaginada.",
      description: "Más que un reproductor de música. Una experiencia digital inmersiva construida con movimiento, interacción y emoción.",
      features: ["UI Inmersiva", "Visualización de Audio", "Interacciones Modernas", "Diseño Responsivo"],
      manifestoLine1: "La música se volvió el medio.",
      manifestoLine2: "La experiencia se volvió el producto.",
    },
    intelligence: {
      label: "INTELIGENCIA",
      titleLine1: "Inteligencia.",
      titleLine2: "Personalizada.",
      description: "Una experiencia adaptativa de aprendizaje diseñada para entender progreso, identificar debilidades y guiar crecimiento.",
      skills: ["Gramática", "Vocabulario", "Escucha", "Habla", "Escritura"],
      insights: ["Aprendizaje Adaptativo", "Guía con IA", "Seguimiento de Progreso", "Feedback Personalizado"],
      manifestoLine1: "El aprendizaje se volvió personal.",
      manifestoLine2: "La inteligencia se volvió adaptativa.",
    },
    control: {
      label: "CONTROL DE MISIÓN",
      titleLine1: "Control.",
      titleLine2: "A Escala.",
      cards: [
        { tag: "ROTAS ESTATICAS", unit: "pages", description: "As paginas de projeto nascem do registry, mantendo o sistema de cases previsivel e facil de expandir.", status: "online", terminal: "next.build --routes" },
        { tag: "REGISTRY DE CASOS", unit: "cases", description: "Cada proyecto posee contenido y entrada de componente propia mientras la ruta sigue generica.", status: "processing", terminal: "registry.resolve --slug", featured: true },
        { tag: "SISTEMA DE CONTENIDO", unit: "langs", description: "El portfolio habla mediante archivos PT, EN y ES en lugar de texto hardcoded en paginas.", status: "secure", terminal: "messages.sync --locales" },
      ],
    },
    evolution: {
      label: "EVOLUCIÓN",
      titleLine1: "De Productos.",
      titleLine2: "A Ecosistemas.",
      description: "Cada proyecto expandió el alcance, la complejidad y la ambición del camino. Juntos revelan una evolución continua en producto, ingeniería y experiencias digitales.",
      milestones: [
        { title: "Experiencia", year: "2024", description: "Creando interfaces memorables. Diseñando interacciones. Construyendo experiencias emocionales." },
        { title: "Inteligencia", year: "2025", description: "Introduciendo IA. Personalizando aprendizaje. Creando sistemas adaptativos." },
        { title: "Control", year: "2025", description: "Escalando complejidad. Gestionando datos. Construyendo plataformas de negocio." },
        { title: "Visión", year: "2026", description: "Conectando productos. Construyendo ecosistemas. Diseñando el futuro." },
      ],
      manifesto: ["De Experiencias", "A Inteligencia", "A Sistemas", "A Ecosistemas"],
    },
    engineering: {
      label: "ADN DE INGENIERÍA",
      titleLine1: "Diseñado",
      titleLine2: "Para Experiencias",
      boot: "INICIALIZANDO ARQUITECTURA NEXUS...",
      description: "Cada producto nace sobre una arquitectura viva donde inteligencia, ingeniería y sistemas escalables convergen en un único ecosistema.",
      layers: [
        { title: "Capa de Experiencia", technologies: ["React", "Next.js", "GSAP", "Framer Motion"] },
        { title: "Capa de Inteligencia", technologies: ["Sistemas de IA", "Prompt Engineering", "OpenAI", "Automatización"] },
        { title: "Capa de Aplicación", technologies: ["Spring Boot", "REST APIs", "Arquitectura", "Lógica de Negocio"] },
        { title: "Capa de Datos", technologies: ["PostgreSQL", "Analytics", "Persistencia", "Modelado"] },
        { title: "Capa de Deploy", technologies: ["Docker", "Cloud", "CI/CD", "Escalabilidad"] },
      ],
      manifestoLine1: "La tecnología no es el destino.",
      manifestoLine2: "Es la base.",
    },
    design: {
      label: "FILOSOFÍA DE DISEÑO",
      titleLine1: "Creado",
      titleLine2: "Con Propósito.",
      descriptionLine1: "Cada interacción, animación y detalle existe por una razón.",
      descriptionLine2: "El diseño no es decoración. Es cómo los productos comunican, guían e inspiran.",
      principles: [
        { title: "Movimiento", description: "El movimiento guía la atención y crea experiencias digitales naturales." },
        { title: "Claridad", description: "Los sistemas complejos deben sentirse intuitivos, simples y ligeros." },
        { title: "Rendimiento", description: "La velocidad no es una feature. Es parte de la experiencia." },
        { title: "Detalles", description: "Pequeñas interacciones crean momentos memorables." },
        { title: "Artesanía", description: "Cada pixel merece intención, precisión y cuidado." },
      ],
      manifestoLine1: "Los productos bellos no nacen por accidente.",
      manifestoLine2: "Se crean con propósito.",
    },
    numbers: {
      label: "EN NÚMEROS",
      titleLine1: "Impacto.",
      titleLine2: "A Escala.",
      description: "Detrás de cada experiencia existe un ecosistema creciente de productos, sistemas, interacciones e ideas.",
      stats: [
        { value: 4, suffix: "", label: "Productos", description: "Conectados por un ecosistema unificado." },
        { value: 150, suffix: "+", label: "Componentes", description: "Creados para construir experiencias escalables." },
        { value: 100, suffix: "+", label: "Animaciones", description: "Diseñadas para fortalecer interacción y narrativa." },
        { value: 30, suffix: "+", label: "Funciones", description: "En productividad, aprendizaje y entretenimiento." },
        { value: 10, suffix: "+", label: "Tecnologías", description: "Trabajando juntas a lo largo del stack." },
        { value: 1, suffix: "", label: "Ecosistema", description: "Una visión conectándolo todo." },
      ],
      manifestoLine1: "Cada número cuenta una historia.",
      manifestoLine2: "Juntos revelan un ecosistema.",
    },
    future: {
      label: "EL FUTURO",
      titleLine1: "ESTO ES SOLO",
      titleLine2: "EL COMIENZO.",
      descriptionLine1: "Construyendo productos. Conectando sistemas. Diseñando experiencias.",
      descriptionLine2: "Creando el futuro, una línea de código a la vez.",
      orbitItems: ["Inteligencia Artificial", "Sistemas Cloud", "Automatización", "Experiencias Mobile", "Design Systems", "Plataformas de Datos", "Innovación de Producto"],
      circularText: "VISIÓN FUTURA • NEXUS CORE • POSIBILIDADES INFINITAS •",
      coreOnline: "CORE ONLINE",
      manifesto: [
        "El camino comenzó con experiencias.",
        "Evolucionó mediante inteligencia.",
        "Escaló a través de sistemas.",
        "Ahora avanza hacia ecosistemas.",
      ],
      manifestoStrong: "El próximo capítulo ya se está escribiendo.",
      status: "Futuro en Progreso",
    },
    final: {
      label: "CAPÍTULO FINAL",
      titleLines: ["VAMOS A CREAR", "ALGO", "MEMORABLE."],
      descriptionLine1: "De ideas a ecosistemas. De conceptos a productos.",
      descriptionLine2: "Creemos el próximo capítulo juntos.",
      status: "Futuro en Progreso",
      pillars: ["Experiencia", "Inteligencia", "Control", "Visión"],
    },
  },
} as const;
